"""Builder — tool-using agent that writes the actual code files.

V2 (D2.2): tool-using agent loop with write_file / read_file / run_command / submit_done.

Mock mode: 走 tools.py(真實 I/O 寫進 sandbox),但檔案內容來自 MOCK_FILES_BY_CATEGORY,
            模擬 agent 的 tool call 軌跡,方便不燒 token 也能 demo。
Real mode: 真的呼叫 Claude API,用 TOOLS_SCHEMA 跑 agent loop,
            直到 submit_done 或達到 max iterations。

D2.4: 若 state["test_results"]["failed"] > 0(retry 進來),會把 errors 加進 prompt,
       並在 mock 模式下提供 trigger keyword 來示範自修 loop。
"""
from __future__ import annotations
import json
from pathlib import Path
from ..state import FactoryState
from ..llm import is_mock, _get_client, MODELS
from ..tools import write_file, run_command, execute_tool, TOOLS_SCHEMA


BUILDER_SYSTEM = """你是 Agent Factory 的 Builder agent。給你 PRD 和系統設計,你要把全部檔案寫到 sandbox。

工作流:
1. 依 design.file_plan,每個檔案用 write_file 寫一份完整內容到 sandbox
2. 全部寫完後,可用 run_command 做最後 sanity check(例如 python -m py_compile main.py)
3. 確認後呼叫 submit_done

規則:
- 程式碼必須真的能跑 — 不要 TODO、不要省略、不要假 import
- 用 type hints
- 加必要的 error handling
- 如果是 Python,只 import 真的存在的套件(stdlib 或 requirements.txt 列的)
- 一次寫一個檔案;看到 tool_result 回 ok 再寫下一個
- 不要回 markdown 解釋,只用 tool 完成工作"""


# ============ MOCK FILES PER CATEGORY ============
# Realistic stub files for the 3 demo paths. Used in mock mode to
# simulate agent output without burning API tokens.

MOCK_FILES_BY_CATEGORY: dict[str, dict[str, str]] = {
    # --- D1: Excel 比對 (桌面 .exe) ---
    "excel_diff": {
        "main.py": '''"""Excel 比對工具 · 桌面入口 · Auto-generated by Agent Factory.

機密採購資料桌面 app。未預期錯誤透過 telemetry.py 上報 schema-only 訊號回
Factory(error type / 檔案 basename / 行號 / OS)· **cell 內容絕不送**。
"""
import sys
import tkinter as tk
from tkinter import messagebox
from gui import DiffWindow
from telemetry import report_exception


def _global_excepthook(exc_type, exc_value, exc_tb):
    """攔截所有未預期錯誤 · 結構訊號上報 · 維持原行為。"""
    if isinstance(exc_value, BaseException):
        report_exception(exc_value)
    sys.__excepthook__(exc_type, exc_value, exc_tb)


def _tk_callback_exception(exc_type, exc_value, exc_tb):
    """Tk 按鈕 callback 拋例外時觸發 · 上報 + 顯示友善對話框。"""
    if isinstance(exc_value, BaseException):
        report_exception(exc_value)
    try:
        messagebox.showerror(
            "錯誤",
            f"發生未預期錯誤: {exc_type.__name__}\\n"
            "結構訊號已上報 (無 cell 內容外洩)"
        )
    except Exception:
        pass


def main() -> None:
    sys.excepthook = _global_excepthook
    root = tk.Tk()
    root.title("採購庫存比對工具")
    root.geometry("720x520")
    root.report_callback_exception = _tk_callback_exception
    DiffWindow(root)
    root.mainloop()


if __name__ == "__main__":
    main()
''',
        "telemetry.py": '''"""Schema-only crash reporter · 給 Factory 用來知道 .exe 哪裡爆。

PRIVACY CONTRACT
----------------
送:
  ✓ error_type (KeyError / ValueError / ...)
  ✓ frames (檔案 basename + 行號 + 函式名)
  ✓ OS 版本
  ✓ app version
不送:
  ✗ cell 內容
  ✗ 完整檔案路徑(只送 basename)
  ✗ 變數值
  ✗ str(exception) (error message 可能含資料)

唯一對外網路通訊的模組。要稽核 / 切掉只看這一個檔。
"""
from __future__ import annotations
import json
import os
import platform
import traceback
import urllib.request


# 公司內部部署時 · 改成內部 server URL · 100% 不走 internet
TELEMETRY_URL = os.environ.get(
    "FACTORY_TELEMETRY_URL",
    "https://agent-factory-web.onrender.com/api/exe_telemetry",
)
APP_NAME = "ExcelDiff"
APP_VERSION = "1.0"


def report_exception(exc: BaseException) -> bool:
    """送一份結構訊號回報。回傳 True 代表成功送出。失敗一律 silent。"""
    try:
        frames = []
        for f in traceback.extract_tb(exc.__traceback__):
            frames.append({
                "file": os.path.basename(f.filename),
                "line": f.lineno,
                "func": f.name,
            })

        payload = {
            "app": APP_NAME,
            "version": APP_VERSION,
            "os": platform.system(),
            "os_release": platform.release(),
            "error_type": type(exc).__name__,
            "frames": frames[-10:],  # 最後 10 個 frame
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            TELEMETRY_URL,
            data=data,
            headers={
                "Content-Type": "application/json",
                "User-Agent": f"{APP_NAME}/{APP_VERSION}",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            return resp.status == 200
    except Exception:
        return False  # telemetry 永不阻擋主程式
''',
        "diff_engine.py": '''"""Pure-Python Excel diff logic. No network. No cloud."""
from __future__ import annotations
import pandas as pd
from pathlib import Path
from typing import Tuple


def load_excel(path: Path) -> pd.DataFrame:
    """Read an .xlsx, handling merged cells gracefully (v0.1.1 patch)."""
    df = pd.read_excel(path, engine="openpyxl")
    df = df.ffill()  # fill merged cells downward
    return df


def diff_dataframes(
    old: pd.DataFrame, new: pd.DataFrame, key: str = "SKU",
) -> dict[str, pd.DataFrame]:
    """Return {added, removed, changed} relative to `key`."""
    old_idx = old.set_index(key)
    new_idx = new.set_index(key)
    added_keys = new_idx.index.difference(old_idx.index)
    removed_keys = old_idx.index.difference(new_idx.index)
    common = new_idx.index.intersection(old_idx.index)
    changed = new_idx.loc[common].compare(old_idx.loc[common])
    return {
        "added": new_idx.loc[added_keys].reset_index(),
        "removed": old_idx.loc[removed_keys].reset_index(),
        "changed": changed.reset_index() if not changed.empty else pd.DataFrame(),
    }


def report_failure_signal(path: Path) -> dict:
    """Send only STRUCTURE info back to Factory if parse fails.

    NEVER includes cell contents — only schema-level signals.
    """
    try:
        import openpyxl
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        signals = {
            "sheet_count": len(wb.sheetnames),
            "first_sheet_rows": wb.active.max_row,
            "first_sheet_cols": wb.active.max_column,
            "merged_cells_count": len(wb.active.merged_cells.ranges),
        }
        return signals
    except Exception as e:
        return {"error_type": type(e).__name__}
''',
        "gui.py": '''"""Tkinter GUI for Excel diff."""
from __future__ import annotations
import tkinter as tk
from tkinter import filedialog, ttk
from pathlib import Path
from diff_engine import load_excel, diff_dataframes


class DiffWindow:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.old_path: Path | None = None
        self.new_path: Path | None = None
        self._build()

    def _build(self) -> None:
        ttk.Button(self.root, text="選舊檔", command=self._pick_old).pack(pady=4)
        ttk.Button(self.root, text="選新檔", command=self._pick_new).pack(pady=4)
        ttk.Button(self.root, text="比對 & 輸出", command=self._run).pack(pady=8)
        self.status = ttk.Label(self.root, text="—")
        self.status.pack(pady=4)

    def _pick_old(self) -> None:
        self.old_path = Path(filedialog.askopenfilename(filetypes=[("Excel", "*.xlsx")]))
        self.status.config(text=f"舊檔: {self.old_path.name}")

    def _pick_new(self) -> None:
        self.new_path = Path(filedialog.askopenfilename(filetypes=[("Excel", "*.xlsx")]))
        self.status.config(text=f"新檔: {self.new_path.name}")

    def _run(self) -> None:
        if not self.old_path or not self.new_path:
            self.status.config(text="請選兩個檔案")
            return
        old = load_excel(self.old_path)
        new = load_excel(self.new_path)
        diff = diff_dataframes(old, new)
        out = self.new_path.with_name(f"diff_{self.new_path.stem}.xlsx")
        with __import__("pandas").ExcelWriter(out, engine="openpyxl") as w:
            for name, df in diff.items():
                df.to_excel(w, sheet_name=name, index=False)
        self.status.config(text=f"完成: {out}")
''',
        "build.spec": '''# PyInstaller spec — bundles main.py into a single Win32 .exe.
# Build with: pyinstaller build.spec
block_cipher = None

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=["openpyxl"],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz, a.scripts, a.binaries, a.zipfiles, a.datas,
    name="ExcelDiff",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=None,
)
''',
        "requirements.txt": "pandas==2.2.3\nopenpyxl==3.1.5\npyinstaller==6.10.0\n",
    },

    # --- D2: 競品戰情室 (Next.js + Redis + crawlers) ---
    "war_room": {
        "package.json": '''{
  "name": "war-room",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "typescript": "5.4.5",
    "@types/react": "18.3.3",
    "@types/node": "20.14.10",
    "tailwindcss": "3.4.7",
    "postcss": "8.4.39",
    "autoprefixer": "10.4.19"
  }
}
''',
        "tailwind.config.ts": '''import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "Noto Sans TC", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
''',
        "postcss.config.js": '''module.exports = {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
''',
        "app/globals.css": '''@tailwind base;
@tailwind components;
@tailwind utilities;

html, body {
  background: #f8fafc;
  color: #0f172a;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

@keyframes pulse-dot {
  0%, 100% { opacity: 1; transform: scale(1); }
  50% { opacity: 0.5; transform: scale(1.4); }
}

.live-dot { animation: pulse-dot 2s ease-in-out infinite; }
''',
        "tsconfig.json": '''{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
''',
        "next.config.js": '''/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
''',
        "app/layout.tsx": '''import "./globals.css";

export const metadata = {
  title: "競品戰情室 · Agent Factory",
  description: "AI 工廠自動產出 · 5 家對手即時監控 · Powered by Claude",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-TW">
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
''',
        "app/page.tsx": '''import { getCompetitors, getDailyBrief, type ThreatLevel } from "@/lib/redis";

export const dynamic = "force-dynamic";

const THREAT_STYLES: Record<ThreatLevel, { label: string; cls: string; emoji: string }> = {
  high:   { label: "高威脅", cls: "bg-rose-50 text-rose-700 ring-rose-200",   emoji: "🔴" },
  medium: { label: "中威脅", cls: "bg-amber-50 text-amber-700 ring-amber-200", emoji: "🟡" },
  low:    { label: "觀察中", cls: "bg-emerald-50 text-emerald-700 ring-emerald-200", emoji: "🟢" },
};

export default async function Home() {
  const [competitors, brief] = await Promise.all([getCompetitors(), getDailyBrief()]);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50/40">
      <div className="max-w-6xl mx-auto px-6 py-12 lg:py-16">

        {/* Header */}
        <header className="mb-10">
          <div className="flex items-center gap-2 mb-3">
            <span className="inline-block w-2 h-2 rounded-full bg-emerald-500 live-dot" />
            <span className="text-[11px] font-bold tracking-[0.15em] uppercase text-emerald-600">
              Live · {brief.date}
            </span>
          </div>
          <h1 className="text-4xl lg:text-5xl font-bold text-slate-900 tracking-tight mb-2">
            競品戰情室
          </h1>
          <p className="text-slate-600 text-base">
            Agent Factory 自動產出 · 5 家對手即時監控
          </p>
          <p className="text-xs text-slate-400 mt-2">
            🕒 上次更新 {brief.lastUpdated} · 下次更新 {brief.nextUpdate} · 台北時區 · Cron 每 15 分鐘
          </p>
        </header>

        {/* AI Brief — hero card */}
        <section className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-600 text-white shadow-xl shadow-violet-500/20 mb-12">
          <div className="absolute -top-24 -right-24 w-72 h-72 bg-white/10 rounded-full blur-3xl pointer-events-none" />
          <div className="absolute -bottom-32 -left-16 w-72 h-72 bg-fuchsia-400/20 rounded-full blur-3xl pointer-events-none" />

          <div className="relative p-8 lg:p-10">
            <div className="flex items-center gap-2 mb-5">
              <span className="text-2xl">✨</span>
              <span className="text-[11px] font-bold tracking-[0.15em] uppercase text-white/85">
                AI 戰情摘要 · {brief.poweredBy}
              </span>
            </div>
            <h2 className="text-2xl lg:text-3xl font-bold leading-snug mb-4">
              {brief.headline}
            </h2>
            <p className="text-base lg:text-lg leading-relaxed text-white/90 mb-6 max-w-4xl">
              {brief.summary}
            </p>
            <div className="inline-flex items-center gap-3 rounded-lg bg-white/10 backdrop-blur-sm px-4 py-3 ring-1 ring-white/20">
              <span className="text-rose-200 font-semibold text-sm">⚠️ 今日最大威脅</span>
              <span className="text-white text-sm">{brief.topThreat}</span>
            </div>
          </div>
        </section>

        {/* Section title */}
        <div className="flex items-end justify-between mb-6">
          <h2 className="text-xl font-bold text-slate-900">5 家對手即時動態</h2>
          <span className="text-xs text-slate-500">每 15 分鐘 Cron 自動更新</span>
        </div>

        {/* Competitor grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {competitors.map((c) => {
            const t = THREAT_STYLES[c.threatLevel];
            const deltaPositive = c.delta > 0;
            return (
              <article
                key={c.name}
                className="group relative flex flex-col gap-4 rounded-2xl bg-white p-6 ring-1 ring-slate-200 shadow-sm hover:shadow-md hover:ring-violet-200 transition-all"
              >
                {/* Top row */}
                <div className="flex items-center justify-between">
                  <h3 className="text-xl font-bold text-slate-900">{c.name}</h3>
                  <span className={`text-[11px] font-semibold px-2.5 py-1 rounded-full ring-1 ${t.cls}`}>
                    {t.emoji} {t.label}
                  </span>
                </div>

                {/* Price + delta */}
                <div className="flex items-baseline gap-3">
                  <div className="text-2xl font-bold text-slate-900">
                    NT$ {c.price.toLocaleString()}
                  </div>
                  <div className={`text-sm font-semibold ${deltaPositive ? "text-emerald-600" : "text-rose-600"}`}>
                    {deltaPositive ? "▲" : "▼"} {Math.abs(c.delta)}%
                  </div>
                </div>

                {/* News link */}
                <a
                  href={c.newsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-slate-700 hover:text-violet-700 border-t border-slate-100 pt-3 inline-flex items-start gap-2 group/link"
                >
                  <span>📰</span>
                  <span className="underline-offset-2 group-hover/link:underline">
                    {c.latestNews}
                    <span className="text-violet-500 ml-1">↗</span>
                  </span>
                </a>

                {/* AI Insight */}
                <div className="rounded-xl bg-gradient-to-br from-violet-50 to-fuchsia-50 ring-1 ring-violet-100 px-4 py-3">
                  <div className="flex items-center gap-1.5 mb-2">
                    <span className="text-sm">✨</span>
                    <span className="text-[10px] font-bold tracking-[0.1em] uppercase text-violet-700">
                      AI 分析
                    </span>
                  </div>
                  <p className="text-[13px] leading-relaxed text-slate-700 mb-2">
                    {c.aiInsight}
                  </p>
                  <a
                    href={c.newsUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs font-semibold text-violet-700 hover:text-violet-900"
                  >
                    → 看原始新聞
                  </a>
                </div>

                {/* Recommended action */}
                <div className="rounded-xl bg-amber-50 ring-1 ring-amber-200 px-4 py-3">
                  <div className="flex items-start gap-2">
                    <span className="text-sm mt-0.5">💡</span>
                    <p className="text-[13px] font-medium text-amber-900 leading-relaxed">
                      {c.recommendedAction}
                    </p>
                  </div>
                </div>
              </article>
            );
          })}
        </div>

        {/* Footer */}
        <footer className="mt-16 pt-6 border-t border-slate-200 text-center text-xs text-slate-400">
          Agent Factory · 一句話 → 5 個 agent 接力 → 上線的 AI 產品
          <br />
          Powered by Claude Sonnet 4.5
        </footer>
      </div>
    </main>
  );
}
''',
        "app/api/competitors/route.ts": '''import { NextResponse } from "next/server";
import { getCompetitors } from "@/lib/redis";

export const dynamic = "force-dynamic";

export async function GET() {
  const data = await getCompetitors();
  return NextResponse.json(data);
}
''',
        "lib/redis.ts": '''export type ThreatLevel = "high" | "medium" | "low";

export type Competitor = {
  name: string;
  price: number;
  delta: number;
  latestNews: string;
  newsUrl: string;
  threatLevel: ThreatLevel;
  aiInsight: string;
  recommendedAction: string;
};

export type DailyBrief = {
  date: string;
  lastUpdated: string;
  nextUpdate: string;
  headline: string;
  summary: string;
  topThreat: string;
  poweredBy: string;
};

// Demo data — Agent Factory 自動產出。生產環境的 scrapers 每 15 分鐘把資料寫進 Redis,
// 並由 Claude Sonnet 4.5 做戰情分析。Demo build 直接用這份 mock。
const MOCK_COMPETITORS: Competitor[] = [
  {
    name: "ACER",
    price: 28900, delta: 2.3,
    latestNews: "Predator X14 旗艦電競發表 · 主打 RTX 5070",
    newsUrl: "https://www.acer.com/tw-zh/predator/laptops/predator-helios-x14",
    threatLevel: "high",
    aiInsight: "Predator X14 切入我們 28-32K 主力價帶,RTX 5070 規格直接對標 ASUS ROG G14。漲價 2.3% 顯示 ACER 對該產品線高度樂觀。",
    recommendedAction: "建議:加速 G14 第三季鋪貨,並在通路備齊行銷 collateral。",
  },
  {
    name: "MSI",
    price: 65900, delta: -1.1,
    latestNews: "暑期 9 折檔期啟動 · 全系列電競筆電適用",
    newsUrl: "https://tw.msi.com/Promotion/index",
    threatLevel: "medium",
    aiInsight: "MSI 全系列降價屬季節性促銷,但 9 折力道偏深,推估目的是清庫存讓位給 9 月新品。",
    recommendedAction: "建議:不跟進降價,主打規格升級 · 同步監測 9 月 MSI 新品。",
  },
  {
    name: "HP",
    price: 42500, delta: 0.5,
    latestNews: "OMEN 16 新色上架 · 玫瑰金/午夜藍",
    newsUrl: "https://www.hp.com/tw-zh/shop/laptops/gaming/omen-16",
    threatLevel: "low",
    aiInsight: "HP 僅做配色更新、無實質規格變動。漲幅 0.5% 為通膨自然推升,非戰略行為。",
    recommendedAction: "建議:持續觀察,無立即應對需求。",
  },
  {
    name: "DELL",
    price: 51900, delta: -2.0,
    latestNews: "Alienware m18 全平台補貨 · 北美亞洲同步",
    newsUrl: "https://www.dell.com/zh-tw/shop/alienware/sf/alienware-laptops",
    threatLevel: "medium",
    aiInsight: "Alienware m18 補貨 + 降價 2%,顯示需求疲軟。DELL 在高階電競筆電市占持續流失。",
    recommendedAction: "建議:鎖定 m18 流失客群 · 推出對應促銷方案吃市占。",
  },
  {
    name: "Lenovo",
    price: 38900, delta: 1.7,
    latestNews: "Legion 7i Pro 上市 · 採用 Intel Core Ultra 9",
    newsUrl: "https://www.lenovo.com/tw/zh/laptops/legion/legion-7-series",
    threatLevel: "high",
    aiInsight: "Legion 7i Pro 首發 Intel Core Ultra 9,搶下 AI PC 心智佔有。Lenovo 站穩中高階電競 + AI PC 雙軌。",
    recommendedAction: "建議:加速 ROG 的 Core Ultra 機型發表 · 行銷聚焦 NPU 應用差異化。",
  },
];

function buildBrief(): DailyBrief {
  const now = new Date();
  const fmt = (d: Date) =>
    d.toLocaleString("zh-TW", { timeZone: "Asia/Taipei", hour12: false, hour: "2-digit", minute: "2-digit" });
  // 對齊到上一個 15 分鐘的整點(模擬最近一次 Cron 觸發)
  const lastTick = new Date(Math.floor(now.getTime() / (15 * 60 * 1000)) * (15 * 60 * 1000));
  const nextTick = new Date(lastTick.getTime() + 15 * 60 * 1000);
  return {
    date: now.toLocaleDateString("zh-TW", { timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit" }),
    lastUpdated: fmt(lastTick),
    nextUpdate: fmt(nextTick),
    headline: "🤖 今日戰情:Lenovo / ACER 雙線壓力 · 高階電競攻防加劇",
    summary:
      "今日 5 家對手有 2 家發動旗艦新品(ACER Predator X14 · Lenovo Legion 7i Pro),共同切入 28-40K 中高階電競筆電價帶。" +
      " MSI 啟動 9 折促銷釋出庫存訊號 · DELL Alienware m18 降價補貨顯示需求疲弱。" +
      " 整體看,我們在中高階電競 + AI PC 雙線都遭受壓力,需在 Q3 強化 ROG 主動產品節奏。",
    topThreat: "Lenovo Legion 7i Pro (Intel Core Ultra 9 首發,AI PC 訴求對標 ASUS)",
    poweredBy: "Claude Sonnet 4.5",
  };
}

export async function getCompetitors(): Promise<Competitor[]> {
  return MOCK_COMPETITORS;
}

export async function getDailyBrief(): Promise<DailyBrief> {
  return buildBrief();
}
''',
        "scrapers/acer.ts": '''// Playwright scraper · run via `npm run scrape` after `npm i -D playwright`.
// Skipped at build time — only invoked from cron.
export async function scrapeAcer() {
  return { name: "ACER", price: 28900, delta: 2.3, latestNews: "Predator X14 發表" };
}
''',
        "scrapers/msi.ts": '''export async function scrapeMsi() {
  return { name: "MSI", price: 65900, delta: -1.1, latestNews: "暑期 9 折" };
}
''',
        "vercel.json": '''{
  "crons": [
    { "path": "/api/refresh", "schedule": "*/15 * * * *" }
  ]
}
''',
    },

    # --- D3: 原物料風險告警 (FastAPI + 多源爬蟲 + LLM 分類 + 推播) ---
    "raw_material_risk": {
        "main.py": '''"""原物料風險告警 · Agent Factory 自動產出。

每 30 分鐘:
  1. 爬地緣 / 油價 / 天災新聞
  2. LLM 分類事件影響的材料
  3. 計算風險分數
  4. 風險升高就推 Slack / Telegram
"""
from __future__ import annotations
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from apscheduler.schedulers.background import BackgroundScheduler
from contextlib import asynccontextmanager
from fetcher import fetch_all_events
from classifier import classify_events
from risk_scorer import update_scores, get_dashboard, get_dashboard_html
from notifier import push_alerts


sched = BackgroundScheduler()


@sched.scheduled_job("interval", minutes=30, id="risk_pulse")
def pulse() -> None:
    events = fetch_all_events()
    classified = classify_events(events)
    deltas = update_scores(classified)
    if deltas.has_alert():
        push_alerts(deltas)


@asynccontextmanager
async def lifespan(_app: FastAPI):
    sched.start()
    yield
    sched.shutdown()


app = FastAPI(title="原物料風險戰情室", lifespan=lifespan)


@app.get("/", response_class=HTMLResponse)
def root() -> HTMLResponse:
    return HTMLResponse(get_dashboard_html())


@app.get("/api/dashboard")
def dashboard() -> dict:
    return get_dashboard()


@app.get("/api/health")
def health() -> dict:
    return {"status": "ok"}
''',
        "fetcher.py": '''"""Multi-source event fetcher.

Pulls from: Google News RSS, oil price feeds, USGS quakes, geopolitical APIs.
"""
from __future__ import annotations
import httpx
from typing import TypedDict


class RawEvent(TypedDict):
    source: str          # "google_news" / "oil_price" / "usgs_quake" / ...
    headline: str
    published_at: str    # ISO
    url: str


SOURCES = {
    "geopolitics_rss":  "https://news.google.com/rss/search?q=geopolitics+oil",
    "supply_chain_rss": "https://news.google.com/rss/search?q=supply+chain+disruption",
    "usgs_quakes":      "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson",
    "oil_brent":        "https://api.eia.gov/v2/petroleum/pri/spt/data/",
}


def fetch_all_events() -> list[RawEvent]:
    out: list[RawEvent] = []
    with httpx.Client(timeout=15.0) as client:
        for source, url in SOURCES.items():
            try:
                r = client.get(url)
                out.extend(_parse(source, r))
            except Exception:
                continue  # skip dead sources, retry next pulse
    return out


def _parse(source: str, response: httpx.Response) -> list[RawEvent]:
    # source-specific parsing (RSS / JSON / GeoJSON)
    # ... (parser implementations) ...
    return []
''',
        "classifier.py": '''"""LLM-based event classifier.

Takes a raw event headline, returns:
  - materials affected (NAND / 銅 / 鋼鐵 / 鋰 / 原油 / ...)
  - severity score
  - estimated impact lag in days
"""
from __future__ import annotations
import os
from typing import TypedDict, Optional


class ClassifiedEvent(TypedDict):
    headline: str
    materials: list[str]      # which materials it affects
    severity: float            # 0.0 - 1.0
    impact_lag_days: int       # how soon procurement feels it
    rationale: str             # for audit


SYSTEM = """你是原物料風險分析師。給你一則新聞,判斷影響哪些採購原料、嚴重度、滯後天數。
回 JSON: {materials: [...], severity: 0-1, impact_lag_days: int, rationale: str}"""


# Lazy init — let module import succeed even when ANTHROPIC_API_KEY is unset
# (e.g. on Render free tier before envs are configured).
_client = None  # type: Optional["Anthropic"]  # noqa: F821


def _get_client():
    global _client
    if _client is None:
        if not os.getenv("ANTHROPIC_API_KEY"):
            return None
        from anthropic import Anthropic
        _client = Anthropic()
    return _client


def classify_events(events: list) -> list[ClassifiedEvent]:
    out: list[ClassifiedEvent] = []
    client = _get_client()
    for ev in events:
        if client is None:
            # Demo / no key: deterministic placeholder so the pipeline keeps moving.
            out.append({
                "headline": ev["headline"],
                "materials": [],
                "severity": 0.0,
                "impact_lag_days": 0,
                "rationale": "(no ANTHROPIC_API_KEY · skipped classification)",
            })
            continue
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=300,
            system=SYSTEM,
            messages=[{"role": "user", "content": ev["headline"]}],
        )
        out.append({
            "headline": ev["headline"], "materials": [], "severity": 0.0,
            "impact_lag_days": 0, "rationale": resp.content[0].text,
        })
    return out
''',
        "risk_scorer.py": '''"""Aggregate classified events into per-material risk scores + render dashboard.

Production:
  Maintains a rolling window. Emits a delta when any material crosses
  LOW / MID / HIGH thresholds. Reads from Redis populated by fetcher.
Demo (this file):
  Uses canned MATERIAL_INSIGHTS for a believable dashboard at /.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from materials import MATERIALS


@dataclass
class RiskDelta:
    material: str
    old_level: str
    new_level: str
    pct_change: float


@dataclass
class RiskSnapshot:
    scores: dict[str, float] = field(default_factory=dict)
    deltas: list[RiskDelta] = field(default_factory=list)

    def has_alert(self) -> bool:
        return any(d.new_level in ("MID", "HIGH") and d.old_level != d.new_level for d in self.deltas)


def update_scores(classified) -> RiskSnapshot:
    return RiskSnapshot()  # placeholder; real impl reads Redis window


# ---------- Canned demo data ----------

MATERIAL_INSIGHTS = {
    "NAND": {
        "level": "HIGH",
        "pct_change": 12.5,
        "sparkline": [40, 42, 45, 48, 52, 58, 63, 68, 72, 78, 82, 88],
        "ai_insight": "韓國三星 Q3 NAND 出貨量年減 8%,搭配 SK 海力士擴產延後,供給端持續吃緊。預期 12 月合約價將漲 5-8%。",
        "recent_event": "三星 NAND 廠定期維護延長至 11 月底",
        "event_url": "https://www.google.com/search?q=Samsung+NAND+production+延長",
        "action": "建議:NAND 庫存補到 90 天安全水位,鎖 12 月合約價。",
    },
    "銅": {
        "level": "MID",
        "pct_change": 5.2,
        "sparkline": [50, 50, 52, 53, 51, 54, 56, 58, 57, 60, 62, 64],
        "ai_insight": "智利 Codelco 罷工進入第 18 天,銅精礦現貨溢價走高。LME 庫存連 6 週下降,短期偏多。",
        "recent_event": "Codelco Andina 礦區罷工持續發酵",
        "event_url": "https://www.google.com/search?q=Codelco+Andina+strike",
        "action": "建議:鎖定 Q4 銅長單,並評估替代鋁材的可行性。",
    },
    "鋼鐵": {
        "level": "LOW",
        "pct_change": -1.5,
        "sparkline": [60, 59, 58, 58, 57, 56, 55, 56, 55, 54, 54, 55],
        "ai_insight": "中國大陸鋼鐵減產 + 建築需求疲軟,熱軋鋼價持平略跌。短期無壓力。",
        "recent_event": "中國大陸 11 月鋼鐵 PMI 49.2",
        "event_url": "https://www.google.com/search?q=China+steel+PMI",
        "action": "建議:暫不需動作,觀察 12 月寶武集團指導價。",
    },
    "鋰": {
        "level": "HIGH",
        "pct_change": 18.3,
        "sparkline": [30, 32, 35, 40, 45, 52, 60, 68, 75, 82, 90, 100],
        "ai_insight": "歐美 EV 補貼回升 + 中國鋰鹽出口減少,碳酸鋰現貨價單月飆漲。電池供應鏈短期吃緊。",
        "recent_event": "贛鋒鋰業限產通告 · Q4 出貨下調 15%",
        "event_url": "https://www.google.com/search?q=lithium+carbonate+price",
        "action": "建議:電池模組成本納入下季 BOM 重估,優先採購寧德時代庫存。",
    },
    "原油": {
        "level": "MID",
        "pct_change": 3.8,
        "sparkline": [70, 72, 73, 71, 74, 75, 77, 76, 78, 79, 80, 81],
        "ai_insight": "OPEC+ 12 月會議延長減產至 Q1,布蘭特油價站穩 $80。地緣風險溢價持續推升。",
        "recent_event": "OPEC+ 延長減產 90 萬桶/日",
        "event_url": "https://www.google.com/search?q=OPEC+production+cut+extension",
        "action": "建議:供應鏈運費成本上調 3% · 塑膠原料採購提前鎖定。",
    },
}


def _now_tpe():
    return datetime.now(timezone(timedelta(hours=8)))


def get_dashboard() -> dict:
    now = _now_tpe()
    last = now.replace(minute=(now.minute // 30) * 30, second=0, microsecond=0)
    nxt = last + timedelta(minutes=30)
    return {
        "updated_at": last.strftime("%Y-%m-%d %H:%M"),
        "next_update": nxt.strftime("%H:%M"),
        "ai_brief": {
            "headline": "🔴 鋰 / NAND 雙線爆衝 · 供應鏈短期承壓",
            "summary": ("鋰價單月狂漲 18.3%(碳酸鋰供需失衡),NAND 漲 12.5%(三星廠維護延長)。"
                        " 銅、原油持續吃緊,鋼鐵唯一持平。本週重點是 Q4 採購合約鎖價窗口。"),
            "top_threat": "鋰價失控(碳酸鋰 +18.3% · 電池模組成本面臨重估)",
            "powered_by": "Claude Sonnet 4.5 · 每 30 分鐘自動更新",
        },
        "materials": [
            {"name": m, **MATERIAL_INSIGHTS[m]} for m in MATERIALS
        ],
    }


# ---------- HTML rendering ----------

def _sparkline_svg(values, color):
    if not values:
        return ""
    w, h = 120, 32
    n = len(values)
    vmin, vmax = min(values), max(values)
    rng = max(vmax - vmin, 1)
    pts = " ".join(
        f"{i * w / max(n - 1, 1):.1f},{h - (v - vmin) / rng * h:.1f}"
        for i, v in enumerate(values)
    )
    return (f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
            f'<polyline fill="none" stroke="{color}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" points="{pts}"/>'
            f'</svg>')


_LEVEL_META = {
    "HIGH": ("rose",    "🔴", "高風險", "#e11d48"),
    "MID":  ("amber",   "🟡", "中風險", "#d97706"),
    "LOW":  ("emerald", "🟢", "低風險", "#059669"),
}


def _render_card(m):
    c, emoji, label, hex_color = _LEVEL_META[m["level"]]
    delta = m["pct_change"]
    delta_str = f"{'+' if delta > 0 else ''}{delta:.1f}%"
    delta_color = hex_color
    spark = _sparkline_svg(m["sparkline"], hex_color)
    return f"""
    <article class="bg-white rounded-2xl p-6 ring-1 ring-slate-200 shadow-sm hover:shadow-md hover:ring-violet-200 transition-all flex flex-col gap-4">
      <div class="flex items-center justify-between">
        <h3 class="text-2xl font-bold text-slate-900">{m["name"]}</h3>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full ring-1 bg-{c}-50 text-{c}-700 ring-{c}-200">
          {emoji} {label}
        </span>
      </div>
      <div class="flex items-end justify-between gap-3">
        <div class="text-3xl font-bold" style="color: {delta_color}">{delta_str}</div>
        <div class="opacity-80">{spark}</div>
      </div>
      <a href="{m["event_url"]}" target="_blank" rel="noopener noreferrer"
        class="text-sm text-slate-700 hover:text-violet-700 border-t border-slate-100 pt-3">
        📰 {m["recent_event"]} <span class="text-violet-500">↗</span>
      </a>
      <div class="rounded-xl bg-gradient-to-br from-violet-50 to-fuchsia-50 ring-1 ring-violet-100 px-4 py-3">
        <div class="text-[10px] font-bold tracking-[0.1em] uppercase text-violet-700 mb-2">✨ AI 分析</div>
        <p class="text-[13px] leading-relaxed text-slate-700">{m["ai_insight"]}</p>
      </div>
      <div class="rounded-xl bg-amber-50 ring-1 ring-amber-200 px-4 py-3">
        <div class="flex items-start gap-2">
          <span>💡</span>
          <p class="text-[13px] font-medium text-amber-900 leading-relaxed">{m["action"]}</p>
        </div>
      </div>
    </article>
    """


def get_dashboard_html() -> str:
    d = get_dashboard()
    brief = d["ai_brief"]
    cards = "".join(_render_card(m) for m in d["materials"])
    return f"""<!DOCTYPE html>
<html lang=\"zh-TW\">
<head>
<meta charset=\"UTF-8\">
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<title>原物料風險戰情室 · Agent Factory</title>
<script src=\"https://cdn.tailwindcss.com\"></script>
<style>
  body {{ font-family: ui-sans-serif, system-ui, -apple-system, \"Noto Sans TC\", sans-serif; }}
  @keyframes pulse-dot {{ 0%, 100% {{ opacity: 1; transform: scale(1); }} 50% {{ opacity: 0.5; transform: scale(1.4); }} }}
  .live-dot {{ animation: pulse-dot 2s ease-in-out infinite; }}
</style>
</head>
<body class=\"min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50/40\">
<main class=\"max-w-6xl mx-auto px-6 py-12 lg:py-16\">

  <header class=\"mb-10\">
    <div class=\"flex items-center gap-2 mb-3\">
      <span class=\"inline-block w-2 h-2 rounded-full bg-emerald-500 live-dot\"></span>
      <span class=\"text-[11px] font-bold tracking-[0.15em] uppercase text-emerald-600\">Live · {d["updated_at"]}</span>
    </div>
    <h1 class=\"text-4xl lg:text-5xl font-bold text-slate-900 tracking-tight mb-2\">原物料風險戰情室</h1>
    <p class=\"text-slate-600\">Agent Factory 自動產出 · 5 種採購原料即時風險監控</p>
    <p class=\"text-xs text-slate-400 mt-2\">🕒 上次更新 {d["updated_at"]} · 下次更新 {d["next_update"]} · Cron 每 30 分鐘 · 台北時區</p>
  </header>

  <section class=\"relative overflow-hidden rounded-2xl bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-600 text-white shadow-xl shadow-violet-500/20 mb-12\">
    <div class=\"absolute -top-24 -right-24 w-72 h-72 bg-white/10 rounded-full blur-3xl pointer-events-none\"></div>
    <div class=\"absolute -bottom-32 -left-16 w-72 h-72 bg-fuchsia-400/20 rounded-full blur-3xl pointer-events-none\"></div>
    <div class=\"relative p-8 lg:p-10\">
      <div class=\"flex items-center gap-2 mb-5\">
        <span class=\"text-2xl\">✨</span>
        <span class=\"text-[11px] font-bold tracking-[0.15em] uppercase text-white/85\">AI 戰情摘要 · {brief["powered_by"]}</span>
      </div>
      <h2 class=\"text-2xl lg:text-3xl font-bold leading-snug mb-4\">{brief["headline"]}</h2>
      <p class=\"text-base lg:text-lg leading-relaxed text-white/90 mb-6 max-w-4xl\">{brief["summary"]}</p>
      <div class=\"inline-flex items-center gap-3 rounded-lg bg-white/10 backdrop-blur-sm px-4 py-3 ring-1 ring-white/20\">
        <span class=\"text-rose-200 font-semibold text-sm\">⚠️ 今日最大威脅</span>
        <span class=\"text-white text-sm\">{brief["top_threat"]}</span>
      </div>
    </div>
  </section>

  <div class=\"flex items-end justify-between mb-6\">
    <h2 class=\"text-xl font-bold text-slate-900\">5 種採購原料即時風險</h2>
    <span class=\"text-xs text-slate-500\">每 30 分鐘 Cron 自動更新</span>
  </div>

  <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5\">
    {cards}
  </div>

  <footer class=\"mt-16 pt-6 border-t border-slate-200 text-center text-xs text-slate-400\">
    Agent Factory · 一句話 → 5 個 agent 接力 → 上線的 AI 產品<br>
    Powered by Claude Sonnet 4.5
  </footer>
</main>
</body>
</html>"""
''',
        "notifier.py": '''"""Push to Slack #procurement-alerts + Telegram fallback."""
from __future__ import annotations
import os
import httpx
from risk_scorer import RiskSnapshot


def push_alerts(snap: RiskSnapshot) -> None:
    msg = _format(snap)
    _push_slack(msg)
    _push_telegram(msg)


def _format(snap: RiskSnapshot) -> str:
    lines = ["🚨 原物料風險警報"]
    for d in snap.deltas:
        arrow = "↗" if d.pct_change > 0 else "↘"
        lines.append(f"• {d.material}  {d.old_level} → {d.new_level}  {arrow}{abs(d.pct_change):.1f}%")
    return "\\n".join(lines)


def _push_slack(text: str) -> None:
    url = os.getenv("SLACK_WEBHOOK_URL")
    if not url:
        return
    httpx.post(url, json={"text": text}, timeout=10.0)


def _push_telegram(text: str) -> None:
    token = os.getenv("TG_BOT_TOKEN")
    chat_id = os.getenv("TG_CHAT_ID")
    if not (token and chat_id):
        return
    httpx.post(
        f"https://api.telegram.org/bot{token}/sendMessage",
        json={"chat_id": chat_id, "text": text},
        timeout=10.0,
    )
''',
        "materials.py": '''"""The 5 raw materials we track for ASUS procurement."""
MATERIALS = ["NAND", "銅", "鋼鐵", "鋰", "原油"]
''',
        "Dockerfile": '''FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
''',
        "requirements.txt": "fastapi==0.115.0\nuvicorn==0.32.0\napscheduler==3.10.4\nhttpx==0.27.2\nanthropic>=0.100.0\n",
    },

    # --- Fallback (monitoring agent, like the original匯率 demo) ---
    "_default": {
        "main.py": '''"""Auto-generated by Agent Factory."""
from fastapi import FastAPI
from apscheduler.schedulers.background import BackgroundScheduler
from fetcher import fetch
from notifier import notify

app = FastAPI()
sched = BackgroundScheduler()


@sched.scheduled_job("interval", minutes=5)
def check() -> None:
    data = fetch()
    if data.get("alert"):
        notify(data["message"])


@app.on_event("startup")
def _start() -> None:
    sched.start()
''',
        "fetcher.py": '''"""Fetch data source. Replace URL with your target."""
import httpx


def fetch() -> dict:
    r = httpx.get("https://api.example.com/data")
    return r.json()
''',
        "notifier.py": '''"""Push to Telegram."""
import os
import httpx


def notify(msg: str) -> None:
    token = os.getenv("TG_TOKEN")
    chat_id = os.getenv("TG_CHAT_ID")
    if not token:
        return
    httpx.post(
        f"https://api.telegram.org/bot{token}/sendMessage",
        json={"chat_id": chat_id, "text": msg},
    )
''',
        "Dockerfile": '''FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
''',
        "requirements.txt": "fastapi==0.115.0\nuvicorn==0.32.0\napscheduler==3.10.4\nhttpx==0.27.2\n",
    },
}


# ============ HELPERS ============

# D2.4 demo trigger — only used in mock mode, so we can show the self-fix loop
# without needing real API. Any of these keywords in user_request will cause
# Builder iteration 0 to inject a syntax error into main.py; iteration 1 fixes it.
_INJECT_FAILURE_KEYWORDS = ["故意", "intentional", "error demo", "import 錯誤", "壞 prompt"]


def _select_files_bundle(subcategory: str) -> dict[str, str]:
    """Pick the right mock bundle based on the PRD subcategory."""
    return MOCK_FILES_BY_CATEGORY.get(subcategory, MOCK_FILES_BY_CATEGORY["_default"])


def _should_inject_failure(user_request: str, iteration: int) -> bool:
    if iteration != 0:
        return False
    return any(k in user_request for k in _INJECT_FAILURE_KEYWORDS)


def _summarize_tool_call(name: str, inp: dict) -> str:
    if name == "write_file":
        return f"write_file {inp.get('path', '?')}"
    if name == "read_file":
        return f"read_file {inp.get('path', '?')}"
    if name == "list_dir":
        return f"list_dir {inp.get('path', '.')}"
    if name == "run_command":
        cmd = inp.get("cmd", "")
        return f"run_command {cmd[:60]}"
    if name == "submit_done":
        return "submit_done"
    return name


def _read_sandbox_files(job_id: str) -> dict[str, str]:
    """Read every text file in generated/{job_id}/ recursively (after agent loop)."""
    root = Path("generated") / job_id
    if not root.exists():
        return {}
    out: dict[str, str] = {}
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        try:
            out[rel] = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
    return out


# ============ MOCK AGENT LOOP ============

def _builder_mock(state: FactoryState, job_id: str, iteration: int, log: list[str]) -> dict[str, str]:
    """Simulate the agent loop in mock mode: real tool calls via tools.py,
    but file contents come from MOCK_FILES_BY_CATEGORY."""
    subcat = state["prd"].get("subcategory", "_default")
    bundle = _select_files_bundle(subcat)
    file_plan = state["design"].get("file_plan") or list(bundle.keys())

    user_request = state.get("user_request", "")
    inject_fail = _should_inject_failure(user_request, iteration)

    written: dict[str, str] = {}
    tool_calls = 0

    for name in file_plan:
        content = bundle.get(name, f"# auto-generated stub for {name}\n")
        if inject_fail and name == "main.py":
            content = content + "\n# D2.4 demo: intentional syntax error\nthis is not valid python at all !!!\n"

        result = write_file(job_id, name, content)
        tool_calls += 1
        if result["ok"]:
            log.append(f"  [tool] write_file {name} ✓")
            written[name] = content
        else:
            log.append(f"  [tool] write_file {name} ✗ ({result['error']})")

    # one verification command — exercise run_command for real
    verify = run_command(job_id, "python --version")
    tool_calls += 1
    check = "✓" if verify["ok"] else "✗"
    log.append(f"  [tool] run_command python --version {check}")

    # signal done
    tool_calls += 1
    log.append(f"  [tool] submit_done ✓")

    log.append(f"✓ Builder: 寫完 {len(written)} 個檔案 · {tool_calls} 次工具呼叫")
    return written


# ============ REAL AGENT LOOP ============

def _builder_real(state: FactoryState, job_id: str, iteration: int, log: list[str]) -> dict[str, str]:
    """Real Claude agent loop with tool use."""
    prd = state["prd"]
    design = state["design"]

    user_msg = (
        f"PRD:\n{json.dumps(prd, ensure_ascii=False, indent=2)}\n\n"
        f"Design:\n{json.dumps(design, ensure_ascii=False, indent=2)}\n\n"
        f"請依 design.file_plan,把每個檔案用 write_file 寫到 sandbox。"
        f"全部寫完後呼叫 submit_done。"
    )

    if iteration > 0:
        prev_errors = state.get("test_results", {}).get("errors", [])
        if prev_errors:
            errors_str = "\n".join(prev_errors)
            user_msg += (
                f"\n\n⚠️ 上一次測試失敗了 (iteration {iteration - 1}),錯誤如下:\n"
                f"{errors_str}\n\n請修正後重新 write_file 把整個檔案重寫。"
            )

    client = _get_client()
    messages: list[dict] = [{"role": "user", "content": user_msg}]

    max_steps = 30
    tool_calls = 0

    for _step in range(max_steps):
        resp = client.messages.create(
            model=MODELS["sonnet"],
            max_tokens=4096,
            system=BUILDER_SYSTEM,
            tools=TOOLS_SCHEMA,
            messages=messages,
        )

        # Echo assistant content back into the conversation (required for tool loops).
        assistant_blocks: list[dict] = []
        for block in resp.content:
            if hasattr(block, "model_dump"):
                assistant_blocks.append(block.model_dump())
            else:
                assistant_blocks.append(block)
        messages.append({"role": "assistant", "content": assistant_blocks})

        if resp.stop_reason == "end_turn":
            break
        if resp.stop_reason != "tool_use":
            break

        tool_results: list[dict] = []
        finished = False

        for block in resp.content:
            if getattr(block, "type", None) != "tool_use":
                continue

            tool_name = block.name
            tool_input = dict(block.input) if block.input else {}
            tool_calls += 1

            result = execute_tool(tool_name, job_id, **tool_input)

            summary = _summarize_tool_call(tool_name, tool_input)
            check = "✓" if result["ok"] else "✗"
            log.append(f"  [tool] {summary} {check}")

            tool_results.append({
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": (result["output"] or result["error"] or "ok")[:1500],
                "is_error": not result["ok"],
            })

            if tool_name == "submit_done":
                finished = True

        messages.append({"role": "user", "content": tool_results})

        if finished:
            break

    written = _read_sandbox_files(job_id)
    log.append(f"✓ Builder: 寫完 {len(written)} 個檔案 · {tool_calls} 次工具呼叫")
    return written


# ============ NODE ENTRYPOINT ============

def builder_node(state: FactoryState) -> FactoryState:
    log = state.get("log", [])
    job_id = state.get("job_id", "unknown")

    # D2.4: bump iteration counter on retry
    iteration = state.get("iteration", 0)
    is_retry = bool(state.get("test_results", {}).get("failed", 0))
    if is_retry:
        iteration = iteration + 1
        log.append(f"⚙️  Builder: 看到 error · 進入 retry iteration {iteration}")
    else:
        log.append("⚙️  Builder: 開始 agent loop...")

    if is_mock():
        files = _builder_mock(state, job_id, iteration, log)
    else:
        files = _builder_real(state, job_id, iteration, log)

    return {
        **state,
        "files": files,
        "iteration": iteration,
        "current_stage": "tester",
        "log": log,
    }
