"""Builder — tool-using agent that writes the actual code files.

V2 (D2.2): tool-using agent loop with write_file / read_file / run_command / submit_done.

Mock mode: 走 tools.py(真實 I/O 寫進 sandbox),但檔案內容來自 MOCK_FILES_BY_CATEGORY,
            模擬 agent 的 tool call 軌跡,方便不燒 token 也能 demo。
Real mode: 真的呼叫 Claude API,用 TOOLS_SCHEMA 跑 agent loop,
            直到 submit_done 或達到 max iterations。

D2.4: 若 state["test_results"]["failed"] > 0(retry 進來),會把 errors 加進 prompt,
       並在 mock 模式下提供 trigger keyword 來示範自修 loop。
"""
from __future__ import annotations
import json
import re
import time
from pathlib import Path
from ..state import FactoryState
from ..llm import is_mock, create_message_with_retry, create_builder_message, MODELS
from ..memory import format_lessons_for_prompt
from ..quality_standards import get_constitution, get_constitution_summary
from ..tools import write_file, run_command, execute_tool, TOOLS_SCHEMA


# REAL 模式下,Builder 進入 Claude call 前等 65 秒 · 給 Azure TPM 視窗(2000/60s)
# 完全清空 Clarifier + Architect 已用的 token
_BUILDER_STARTUP_DELAY = 65.0


BUILDER_SYSTEM = """你是 Agent Factory 的 Builder agent。給你 PRD 和系統設計,你要把全部檔案寫到 sandbox。

工作流:
1. 依 design.file_plan,每個檔案用 write_file 寫一份完整內容到 sandbox
2. 全部寫完後,可用 run_command 做最後 sanity check(例如 python -m py_compile main.py)
3. 確認後呼叫 submit_done

規則:
- 程式碼必須真的能跑 — 不要 TODO、不要省略、不要假 import
- 用 type hints
- 加必要的 error handling
- 如果是 Python,只 import 真的存在的套件(stdlib 或 requirements.txt 列的)
- 一次寫一個檔案;看到 tool_result 回 ok 再寫下一個
- 不要回 markdown 解釋,只用 tool 完成工作"""


# ============ MOCK FILES PER CATEGORY ============
# Realistic stub files for the 3 demo paths. Used in mock mode to
# simulate agent output without burning API tokens.

MOCK_FILES_BY_CATEGORY: dict[str, dict[str, str]] = {
    # --- D1: Excel 比對 (桌面 .exe) ---
    "excel_diff": {
        "main.py": '''"""Excel 比對工具 · 桌面入口 · Auto-generated by Agent Factory.

機密採購資料桌面 app。未預期錯誤透過 telemetry.py 上報 schema-only 訊號回
Factory(error type / 檔案 basename / 行號 / OS)· **cell 內容絕不送**。
"""
import sys
import tkinter as tk
from tkinter import messagebox
from gui import DiffWindow
from telemetry import report_exception


def _global_excepthook(exc_type, exc_value, exc_tb):
    """攔截所有未預期錯誤 · 結構訊號上報 · 維持原行為。"""
    if isinstance(exc_value, BaseException):
        report_exception(exc_value)
    sys.__excepthook__(exc_type, exc_value, exc_tb)


def _tk_callback_exception(exc_type, exc_value, exc_tb):
    """Tk 按鈕 callback 拋例外時觸發 · 上報 + 顯示友善對話框。"""
    if isinstance(exc_value, BaseException):
        report_exception(exc_value)
    try:
        messagebox.showerror(
            "錯誤",
            f"發生未預期錯誤: {exc_type.__name__}\\n"
            "結構訊號已上報 (無 cell 內容外洩)"
        )
    except Exception:
        pass


def main() -> None:
    sys.excepthook = _global_excepthook
    root = tk.Tk()
    root.title("採購庫存比對工具")
    root.geometry("720x520")
    root.report_callback_exception = _tk_callback_exception
    DiffWindow(root)
    root.mainloop()


if __name__ == "__main__":
    main()
''',
        "telemetry.py": '''"""Schema-only crash reporter · 給 Factory 用來知道 .exe 哪裡爆。

PRIVACY CONTRACT
----------------
送:
  ✓ error_type (KeyError / ValueError / ...)
  ✓ frames (檔案 basename + 行號 + 函式名)
  ✓ OS 版本
  ✓ app version
不送:
  ✗ cell 內容
  ✗ 完整檔案路徑(只送 basename)
  ✗ 變數值
  ✗ str(exception) (error message 可能含資料)

唯一對外網路通訊的模組。要稽核 / 切掉只看這一個檔。
"""
from __future__ import annotations
import json
import os
import platform
import traceback
import urllib.request


# 公司內部部署時 · 改成內部 server URL · 100% 不走 internet
TELEMETRY_URL = os.environ.get(
    "FACTORY_TELEMETRY_URL",
    "https://agent-factory-web.onrender.com/api/exe_telemetry",
)
APP_NAME = "ExcelDiff"
APP_VERSION = "1.0"


def report_exception(exc: BaseException) -> bool:
    """送一份結構訊號回報。回傳 True 代表成功送出。失敗一律 silent。"""
    try:
        frames = []
        for f in traceback.extract_tb(exc.__traceback__):
            frames.append({
                "file": os.path.basename(f.filename),
                "line": f.lineno,
                "func": f.name,
            })

        payload = {
            "app": APP_NAME,
            "version": APP_VERSION,
            "os": platform.system(),
            "os_release": platform.release(),
            "error_type": type(exc).__name__,
            "frames": frames[-10:],  # 最後 10 個 frame
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            TELEMETRY_URL,
            data=data,
            headers={
                "Content-Type": "application/json",
                "User-Agent": f"{APP_NAME}/{APP_VERSION}",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            return resp.status == 200
    except Exception:
        return False  # telemetry 永不阻擋主程式
''',
        "diff_engine.py": '''"""Pure-Python Excel diff logic. No network. No cloud."""
from __future__ import annotations
import pandas as pd
from pathlib import Path
from typing import Tuple


def load_excel(path: Path) -> pd.DataFrame:
    """Read an .xlsx, handling merged cells gracefully (v0.1.1 patch)."""
    df = pd.read_excel(path, engine="openpyxl")
    df = df.ffill()  # fill merged cells downward
    return df


def diff_dataframes(
    old: pd.DataFrame, new: pd.DataFrame, key: str = "SKU",
) -> dict[str, pd.DataFrame]:
    """Return {added, removed, changed} relative to `key`."""
    old_idx = old.set_index(key)
    new_idx = new.set_index(key)
    added_keys = new_idx.index.difference(old_idx.index)
    removed_keys = old_idx.index.difference(new_idx.index)
    common = new_idx.index.intersection(old_idx.index)
    changed = new_idx.loc[common].compare(old_idx.loc[common])
    return {
        "added": new_idx.loc[added_keys].reset_index(),
        "removed": old_idx.loc[removed_keys].reset_index(),
        "changed": changed.reset_index() if not changed.empty else pd.DataFrame(),
    }


def report_failure_signal(path: Path) -> dict:
    """Send only STRUCTURE info back to Factory if parse fails.

    NEVER includes cell contents — only schema-level signals.
    """
    try:
        import openpyxl
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        signals = {
            "sheet_count": len(wb.sheetnames),
            "first_sheet_rows": wb.active.max_row,
            "first_sheet_cols": wb.active.max_column,
            "merged_cells_count": len(wb.active.merged_cells.ranges),
        }
        return signals
    except Exception as e:
        return {"error_type": type(e).__name__}
''',
        "gui.py": '''"""Tkinter GUI for Excel diff."""
from __future__ import annotations
import tkinter as tk
from tkinter import filedialog, ttk
from pathlib import Path
from diff_engine import load_excel, diff_dataframes


class DiffWindow:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.old_path: Path | None = None
        self.new_path: Path | None = None
        self._build()

    def _build(self) -> None:
        ttk.Button(self.root, text="選舊檔", command=self._pick_old).pack(pady=4)
        ttk.Button(self.root, text="選新檔", command=self._pick_new).pack(pady=4)
        ttk.Button(self.root, text="比對 & 輸出", command=self._run).pack(pady=8)
        self.status = ttk.Label(self.root, text="—")
        self.status.pack(pady=4)

    def _pick_old(self) -> None:
        self.old_path = Path(filedialog.askopenfilename(filetypes=[("Excel", "*.xlsx")]))
        self.status.config(text=f"舊檔: {self.old_path.name}")

    def _pick_new(self) -> None:
        self.new_path = Path(filedialog.askopenfilename(filetypes=[("Excel", "*.xlsx")]))
        self.status.config(text=f"新檔: {self.new_path.name}")

    def _run(self) -> None:
        if not self.old_path or not self.new_path:
            self.status.config(text="請選兩個檔案")
            return
        old = load_excel(self.old_path)
        new = load_excel(self.new_path)
        diff = diff_dataframes(old, new)
        out = self.new_path.with_name(f"diff_{self.new_path.stem}.xlsx")
        with __import__("pandas").ExcelWriter(out, engine="openpyxl") as w:
            for name, df in diff.items():
                df.to_excel(w, sheet_name=name, index=False)
        self.status.config(text=f"完成: {out}")
''',
        "build.spec": '''# PyInstaller spec — bundles main.py into a single Win32 .exe.
# Build with: pyinstaller build.spec
block_cipher = None

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=["openpyxl"],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz, a.scripts, a.binaries, a.zipfiles, a.datas,
    name="ExcelDiff",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=None,
)
''',
        "requirements.txt": "pandas==2.2.3\nopenpyxl==3.1.5\npyinstaller==6.10.0\n",
    },

    # --- D2: 競品戰情室 (Next.js + Redis + crawlers) ---
    "war_room": {
        "package.json": '''{
  "name": "war-room",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "typescript": "5.4.5",
    "@types/react": "18.3.3",
    "@types/node": "20.14.10",
    "tailwindcss": "3.4.7",
    "postcss": "8.4.39",
    "autoprefixer": "10.4.19"
  }
}
''',
        "tailwind.config.ts": '''import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "Noto Sans TC", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
''',
        "postcss.config.js": '''module.exports = {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
''',
        "app/globals.css": '''@tailwind base;
@tailwind components;
@tailwind utilities;

html, body {
  background: #f8fafc;
  color: #0f172a;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

@keyframes pulse-dot {
  0%, 100% { opacity: 1; transform: scale(1); }
  50% { opacity: 0.5; transform: scale(1.4); }
}

.live-dot { animation: pulse-dot 2s ease-in-out infinite; }
''',
        "tsconfig.json": '''{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
''',
        "next.config.js": '''/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
''',
        "app/layout.tsx": '''import "./globals.css";

export const metadata = {
  title: "競品戰情室 · Agent Factory",
  description: "AI 工廠自動產出 · 5 家對手即時監控 · Powered by Claude",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-TW">
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
''',
        "app/page.tsx": '''import { getCompetitors, getDailyBrief, type ThreatLevel } from "@/lib/redis";

export const dynamic = "force-dynamic";

const THREAT_STYLES: Record<ThreatLevel, { label: string; cls: string; emoji: string }> = {
  high:   { label: "高威脅", cls: "bg-rose-50 text-rose-700 ring-rose-200",   emoji: "🔴" },
  medium: { label: "中威脅", cls: "bg-amber-50 text-amber-700 ring-amber-200", emoji: "🟡" },
  low:    { label: "觀察中", cls: "bg-emerald-50 text-emerald-700 ring-emerald-200", emoji: "🟢" },
};

export default async function Home() {
  const [competitors, brief] = await Promise.all([getCompetitors(), getDailyBrief()]);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50/40">
      <div className="max-w-6xl mx-auto px-6 py-12 lg:py-16">

        {/* Header */}
        <header className="mb-10">
          <div className="flex items-center gap-2 mb-3">
            <span className="inline-block w-2 h-2 rounded-full bg-emerald-500 live-dot" />
            <span className="text-[11px] font-bold tracking-[0.15em] uppercase text-emerald-600">
              Live · {brief.date}
            </span>
          </div>
          <h1 className="text-4xl lg:text-5xl font-bold text-slate-900 tracking-tight mb-2">
            競品戰情室
          </h1>
          <p className="text-slate-600 text-base">
            Agent Factory 自動產出 · 5 家對手即時監控
          </p>
          <p className="text-xs text-slate-400 mt-2">
            🕒 上次更新 {brief.lastUpdated} · 下次更新 {brief.nextUpdate} · 台北時區 · Cron 每 15 分鐘
          </p>
        </header>

        {/* AI Brief — hero card */}
        <section className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-600 text-white shadow-xl shadow-violet-500/20 mb-12">
          <div className="absolute -top-24 -right-24 w-72 h-72 bg-white/10 rounded-full blur-3xl pointer-events-none" />
          <div className="absolute -bottom-32 -left-16 w-72 h-72 bg-fuchsia-400/20 rounded-full blur-3xl pointer-events-none" />

          <div className="relative p-8 lg:p-10">
            <div className="flex items-center gap-2 mb-5">
              <span className="text-2xl">✨</span>
              <span className="text-[11px] font-bold tracking-[0.15em] uppercase text-white/85">
                AI 戰情摘要 · {brief.poweredBy}
              </span>
            </div>
            <h2 className="text-2xl lg:text-3xl font-bold leading-snug mb-4">
              {brief.headline}
            </h2>
            <p className="text-base lg:text-lg leading-relaxed text-white/90 mb-6 max-w-4xl">
              {brief.summary}
            </p>
            <div className="inline-flex items-center gap-3 rounded-lg bg-white/10 backdrop-blur-sm px-4 py-3 ring-1 ring-white/20">
              <span className="text-rose-200 font-semibold text-sm">⚠️ 今日最大威脅</span>
              <span className="text-white text-sm">{brief.topThreat}</span>
            </div>
          </div>
        </section>

        {/* Section title */}
        <div className="flex items-end justify-between mb-6">
          <h2 className="text-xl font-bold text-slate-900">5 家對手即時動態</h2>
          <span className="text-xs text-slate-500">每 15 分鐘 Cron 自動更新</span>
        </div>

        {/* Competitor grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {competitors.map((c) => {
            const t = THREAT_STYLES[c.threatLevel];
            const deltaPositive = c.delta > 0;
            return (
              <article
                key={c.name}
                className="group relative flex flex-col gap-4 rounded-2xl bg-white p-6 ring-1 ring-slate-200 shadow-sm hover:shadow-md hover:ring-violet-200 transition-all"
              >
                {/* Top row */}
                <div className="flex items-center justify-between">
                  <h3 className="text-xl font-bold text-slate-900">{c.name}</h3>
                  <span className={`text-[11px] font-semibold px-2.5 py-1 rounded-full ring-1 ${t.cls}`}>
                    {t.emoji} {t.label}
                  </span>
                </div>

                {/* Price + delta */}
                <div className="flex items-baseline gap-3">
                  <div className="text-2xl font-bold text-slate-900">
                    NT$ {c.price.toLocaleString()}
                  </div>
                  <div className={`text-sm font-semibold ${deltaPositive ? "text-emerald-600" : "text-rose-600"}`}>
                    {deltaPositive ? "▲" : "▼"} {Math.abs(c.delta)}%
                  </div>
                </div>

                {/* News link */}
                <a
                  href={c.newsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-slate-700 hover:text-violet-700 border-t border-slate-100 pt-3 inline-flex items-start gap-2 group/link"
                >
                  <span>📰</span>
                  <span className="underline-offset-2 group-hover/link:underline">
                    {c.latestNews}
                    <span className="text-violet-500 ml-1">↗</span>
                  </span>
                </a>

                {/* AI Insight */}
                <div className="rounded-xl bg-gradient-to-br from-violet-50 to-fuchsia-50 ring-1 ring-violet-100 px-4 py-3">
                  <div className="flex items-center gap-1.5 mb-2">
                    <span className="text-sm">✨</span>
                    <span className="text-[10px] font-bold tracking-[0.1em] uppercase text-violet-700">
                      AI 分析
                    </span>
                  </div>
                  <p className="text-[13px] leading-relaxed text-slate-700 mb-2">
                    {c.aiInsight}
                  </p>
                  <a
                    href={c.newsUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs font-semibold text-violet-700 hover:text-violet-900"
                  >
                    → 看原始新聞
                  </a>
                </div>

                {/* Recommended action */}
                <div className="rounded-xl bg-amber-50 ring-1 ring-amber-200 px-4 py-3">
                  <div className="flex items-start gap-2">
                    <span className="text-sm mt-0.5">💡</span>
                    <p className="text-[13px] font-medium text-amber-900 leading-relaxed">
                      {c.recommendedAction}
                    </p>
                  </div>
                </div>
              </article>
            );
          })}
        </div>

        {/* Footer */}
        <footer className="mt-16 pt-6 border-t border-slate-200 text-center text-xs text-slate-400">
          Agent Factory · 一句話 → 5 個 agent 接力 → 上線的 AI 產品
          <br />
          Powered by Claude Sonnet 4.5
        </footer>
      </div>
    </main>
  );
}
''',
        "app/api/competitors/route.ts": '''import { NextResponse } from "next/server";
import { getCompetitors } from "@/lib/redis";

export const dynamic = "force-dynamic";

export async function GET() {
  const data = await getCompetitors();
  return NextResponse.json(data);
}
''',
        "lib/redis.ts": '''export type ThreatLevel = "high" | "medium" | "low";

export type Competitor = {
  name: string;
  price: number;
  delta: number;
  latestNews: string;
  newsUrl: string;
  threatLevel: ThreatLevel;
  aiInsight: string;
  recommendedAction: string;
};

export type DailyBrief = {
  date: string;
  lastUpdated: string;
  nextUpdate: string;
  headline: string;
  summary: string;
  topThreat: string;
  poweredBy: string;
};

// Demo data — Agent Factory 自動產出。生產環境的 scrapers 每 15 分鐘把資料寫進 Redis,
// 並由 Claude Sonnet 4.5 做戰情分析。Demo build 直接用這份 mock。
const MOCK_COMPETITORS: Competitor[] = [
  {
    name: "ACER",
    price: 28900, delta: 2.3,
    latestNews: "Predator X14 旗艦電競發表 · 主打 RTX 5070",
    newsUrl: "https://www.acer.com/tw-zh/predator/laptops/predator-helios-x14",
    threatLevel: "high",
    aiInsight: "Predator X14 切入我們 28-32K 主力價帶,RTX 5070 規格直接對標 ASUS ROG G14。漲價 2.3% 顯示 ACER 對該產品線高度樂觀。",
    recommendedAction: "建議:加速 G14 第三季鋪貨,並在通路備齊行銷 collateral。",
  },
  {
    name: "MSI",
    price: 65900, delta: -1.1,
    latestNews: "暑期 9 折檔期啟動 · 全系列電競筆電適用",
    newsUrl: "https://tw.msi.com/Promotion/index",
    threatLevel: "medium",
    aiInsight: "MSI 全系列降價屬季節性促銷,但 9 折力道偏深,推估目的是清庫存讓位給 9 月新品。",
    recommendedAction: "建議:不跟進降價,主打規格升級 · 同步監測 9 月 MSI 新品。",
  },
  {
    name: "HP",
    price: 42500, delta: 0.5,
    latestNews: "OMEN 16 新色上架 · 玫瑰金/午夜藍",
    newsUrl: "https://www.hp.com/tw-zh/shop/laptops/gaming/omen-16",
    threatLevel: "low",
    aiInsight: "HP 僅做配色更新、無實質規格變動。漲幅 0.5% 為通膨自然推升,非戰略行為。",
    recommendedAction: "建議:持續觀察,無立即應對需求。",
  },
  {
    name: "DELL",
    price: 51900, delta: -2.0,
    latestNews: "Alienware m18 全平台補貨 · 北美亞洲同步",
    newsUrl: "https://www.dell.com/zh-tw/shop/alienware/sf/alienware-laptops",
    threatLevel: "medium",
    aiInsight: "Alienware m18 補貨 + 降價 2%,顯示需求疲軟。DELL 在高階電競筆電市占持續流失。",
    recommendedAction: "建議:鎖定 m18 流失客群 · 推出對應促銷方案吃市占。",
  },
  {
    name: "Lenovo",
    price: 38900, delta: 1.7,
    latestNews: "Legion 7i Pro 上市 · 採用 Intel Core Ultra 9",
    newsUrl: "https://www.lenovo.com/tw/zh/laptops/legion/legion-7-series",
    threatLevel: "high",
    aiInsight: "Legion 7i Pro 首發 Intel Core Ultra 9,搶下 AI PC 心智佔有。Lenovo 站穩中高階電競 + AI PC 雙軌。",
    recommendedAction: "建議:加速 ROG 的 Core Ultra 機型發表 · 行銷聚焦 NPU 應用差異化。",
  },
];

function buildBrief(): DailyBrief {
  const now = new Date();
  const fmt = (d: Date) =>
    d.toLocaleString("zh-TW", { timeZone: "Asia/Taipei", hour12: false, hour: "2-digit", minute: "2-digit" });
  // 對齊到上一個 15 分鐘的整點(模擬最近一次 Cron 觸發)
  const lastTick = new Date(Math.floor(now.getTime() / (15 * 60 * 1000)) * (15 * 60 * 1000));
  const nextTick = new Date(lastTick.getTime() + 15 * 60 * 1000);
  return {
    date: now.toLocaleDateString("zh-TW", { timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit" }),
    lastUpdated: fmt(lastTick),
    nextUpdate: fmt(nextTick),
    headline: "🤖 今日戰情:Lenovo / ACER 雙線壓力 · 高階電競攻防加劇",
    summary:
      "今日 5 家對手有 2 家發動旗艦新品(ACER Predator X14 · Lenovo Legion 7i Pro),共同切入 28-40K 中高階電競筆電價帶。" +
      " MSI 啟動 9 折促銷釋出庫存訊號 · DELL Alienware m18 降價補貨顯示需求疲弱。" +
      " 整體看,我們在中高階電競 + AI PC 雙線都遭受壓力,需在 Q3 強化 ROG 主動產品節奏。",
    topThreat: "Lenovo Legion 7i Pro (Intel Core Ultra 9 首發,AI PC 訴求對標 ASUS)",
    poweredBy: "Claude Sonnet 4.5",
  };
}

export async function getCompetitors(): Promise<Competitor[]> {
  return MOCK_COMPETITORS;
}

export async function getDailyBrief(): Promise<DailyBrief> {
  return buildBrief();
}
''',
        "scrapers/acer.ts": '''// Playwright scraper · run via `npm run scrape` after `npm i -D playwright`.
// Skipped at build time — only invoked from cron.
export async function scrapeAcer() {
  return { name: "ACER", price: 28900, delta: 2.3, latestNews: "Predator X14 發表" };
}
''',
        "scrapers/msi.ts": '''export async function scrapeMsi() {
  return { name: "MSI", price: 65900, delta: -1.1, latestNews: "暑期 9 折" };
}
''',
        "vercel.json": '''{
  "crons": [
    { "path": "/api/refresh", "schedule": "*/15 * * * *" }
  ]
}
''',
    },

    # --- D3: 原物料風險告警 (FastAPI + 多源爬蟲 + LLM 分類 + 推播) ---
    "raw_material_risk": {
        "main.py": '''"""原物料風險告警 · Agent Factory 自動產出。

每 30 分鐘:
  1. 爬地緣 / 油價 / 天災新聞
  2. LLM 分類事件影響的材料
  3. 計算風險分數
  4. 風險升高就推 Slack / Telegram
"""
from __future__ import annotations
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from apscheduler.schedulers.background import BackgroundScheduler
from contextlib import asynccontextmanager
from fetcher import fetch_all_events
from classifier import classify_events
from risk_scorer import update_scores, get_dashboard, get_dashboard_html
from notifier import push_alerts


sched = BackgroundScheduler()


@sched.scheduled_job("interval", minutes=30, id="risk_pulse")
def pulse() -> None:
    events = fetch_all_events()
    classified = classify_events(events)
    deltas = update_scores(classified)
    if deltas.has_alert():
        push_alerts(deltas)


@asynccontextmanager
async def lifespan(_app: FastAPI):
    sched.start()
    yield
    sched.shutdown()


app = FastAPI(title="原物料風險戰情室", lifespan=lifespan)


@app.get("/", response_class=HTMLResponse)
def root() -> HTMLResponse:
    return HTMLResponse(get_dashboard_html())


@app.get("/api/dashboard")
def dashboard() -> dict:
    return get_dashboard()


@app.get("/api/health")
def health() -> dict:
    return {"status": "ok"}
''',
        "fetcher.py": '''"""Multi-source event fetcher.

Pulls from: Google News RSS, oil price feeds, USGS quakes, geopolitical APIs.
"""
from __future__ import annotations
import httpx
from typing import TypedDict


class RawEvent(TypedDict):
    source: str          # "google_news" / "oil_price" / "usgs_quake" / ...
    headline: str
    published_at: str    # ISO
    url: str


SOURCES = {
    "geopolitics_rss":  "https://news.google.com/rss/search?q=geopolitics+oil",
    "supply_chain_rss": "https://news.google.com/rss/search?q=supply+chain+disruption",
    "usgs_quakes":      "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson",
    "oil_brent":        "https://api.eia.gov/v2/petroleum/pri/spt/data/",
}


def fetch_all_events() -> list[RawEvent]:
    out: list[RawEvent] = []
    with httpx.Client(timeout=15.0) as client:
        for source, url in SOURCES.items():
            try:
                r = client.get(url)
                out.extend(_parse(source, r))
            except Exception:
                continue  # skip dead sources, retry next pulse
    return out


def _parse(source: str, response: httpx.Response) -> list[RawEvent]:
    # source-specific parsing (RSS / JSON / GeoJSON)
    # ... (parser implementations) ...
    return []
''',
        "classifier.py": '''"""LLM-based event classifier.

Takes a raw event headline, returns:
  - materials affected (NAND / 銅 / 鋼鐵 / 鋰 / 原油 / ...)
  - severity score
  - estimated impact lag in days
"""
from __future__ import annotations
import os
from typing import TypedDict, Optional


class ClassifiedEvent(TypedDict):
    headline: str
    materials: list[str]      # which materials it affects
    severity: float            # 0.0 - 1.0
    impact_lag_days: int       # how soon procurement feels it
    rationale: str             # for audit


SYSTEM = """你是原物料風險分析師。給你一則新聞,判斷影響哪些採購原料、嚴重度、滯後天數。
回 JSON: {materials: [...], severity: 0-1, impact_lag_days: int, rationale: str}"""


# Lazy init — let module import succeed even when ANTHROPIC_API_KEY is unset
# (e.g. on Render free tier before envs are configured).
_client = None  # type: Optional["Anthropic"]  # noqa: F821


def _get_client():
    global _client
    if _client is None:
        if not os.getenv("ANTHROPIC_API_KEY"):
            return None
        from anthropic import Anthropic
        _client = Anthropic()
    return _client


def classify_events(events: list) -> list[ClassifiedEvent]:
    out: list[ClassifiedEvent] = []
    client = _get_client()
    for ev in events:
        if client is None:
            # Demo / no key: deterministic placeholder so the pipeline keeps moving.
            out.append({
                "headline": ev["headline"],
                "materials": [],
                "severity": 0.0,
                "impact_lag_days": 0,
                "rationale": "(no ANTHROPIC_API_KEY · skipped classification)",
            })
            continue
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=300,
            system=SYSTEM,
            messages=[{"role": "user", "content": ev["headline"]}],
        )
        out.append({
            "headline": ev["headline"], "materials": [], "severity": 0.0,
            "impact_lag_days": 0, "rationale": resp.content[0].text,
        })
    return out
''',
        "risk_scorer.py": '''"""Aggregate classified events into per-material risk scores + render dashboard.

Production:
  Maintains a rolling window. Emits a delta when any material crosses
  LOW / MID / HIGH thresholds. Reads from Redis populated by fetcher.
Demo (this file):
  Uses canned MATERIAL_INSIGHTS for a believable dashboard at /.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from materials import MATERIALS


@dataclass
class RiskDelta:
    material: str
    old_level: str
    new_level: str
    pct_change: float


@dataclass
class RiskSnapshot:
    scores: dict[str, float] = field(default_factory=dict)
    deltas: list[RiskDelta] = field(default_factory=list)

    def has_alert(self) -> bool:
        return any(d.new_level in ("MID", "HIGH") and d.old_level != d.new_level for d in self.deltas)


def update_scores(classified) -> RiskSnapshot:
    return RiskSnapshot()  # placeholder; real impl reads Redis window


# ---------- Canned demo data ----------

MATERIAL_INSIGHTS = {
    "NAND": {
        "level": "HIGH",
        "pct_change": 12.5,
        "sparkline": [40, 42, 45, 48, 52, 58, 63, 68, 72, 78, 82, 88],
        "ai_insight": "韓國三星 Q3 NAND 出貨量年減 8%,搭配 SK 海力士擴產延後,供給端持續吃緊。預期 12 月合約價將漲 5-8%。",
        "recent_event": "三星 NAND 廠定期維護延長至 11 月底",
        "event_url": "https://www.google.com/search?q=Samsung+NAND+production+延長",
        "action": "建議:NAND 庫存補到 90 天安全水位,鎖 12 月合約價。",
    },
    "銅": {
        "level": "MID",
        "pct_change": 5.2,
        "sparkline": [50, 50, 52, 53, 51, 54, 56, 58, 57, 60, 62, 64],
        "ai_insight": "智利 Codelco 罷工進入第 18 天,銅精礦現貨溢價走高。LME 庫存連 6 週下降,短期偏多。",
        "recent_event": "Codelco Andina 礦區罷工持續發酵",
        "event_url": "https://www.google.com/search?q=Codelco+Andina+strike",
        "action": "建議:鎖定 Q4 銅長單,並評估替代鋁材的可行性。",
    },
    "鋼鐵": {
        "level": "LOW",
        "pct_change": -1.5,
        "sparkline": [60, 59, 58, 58, 57, 56, 55, 56, 55, 54, 54, 55],
        "ai_insight": "中國大陸鋼鐵減產 + 建築需求疲軟,熱軋鋼價持平略跌。短期無壓力。",
        "recent_event": "中國大陸 11 月鋼鐵 PMI 49.2",
        "event_url": "https://www.google.com/search?q=China+steel+PMI",
        "action": "建議:暫不需動作,觀察 12 月寶武集團指導價。",
    },
    "鋰": {
        "level": "HIGH",
        "pct_change": 18.3,
        "sparkline": [30, 32, 35, 40, 45, 52, 60, 68, 75, 82, 90, 100],
        "ai_insight": "歐美 EV 補貼回升 + 中國鋰鹽出口減少,碳酸鋰現貨價單月飆漲。電池供應鏈短期吃緊。",
        "recent_event": "贛鋒鋰業限產通告 · Q4 出貨下調 15%",
        "event_url": "https://www.google.com/search?q=lithium+carbonate+price",
        "action": "建議:電池模組成本納入下季 BOM 重估,優先採購寧德時代庫存。",
    },
    "原油": {
        "level": "MID",
        "pct_change": 3.8,
        "sparkline": [70, 72, 73, 71, 74, 75, 77, 76, 78, 79, 80, 81],
        "ai_insight": "OPEC+ 12 月會議延長減產至 Q1,布蘭特油價站穩 $80。地緣風險溢價持續推升。",
        "recent_event": "OPEC+ 延長減產 90 萬桶/日",
        "event_url": "https://www.google.com/search?q=OPEC+production+cut+extension",
        "action": "建議:供應鏈運費成本上調 3% · 塑膠原料採購提前鎖定。",
    },
}


def _now_tpe():
    return datetime.now(timezone(timedelta(hours=8)))


def get_dashboard() -> dict:
    now = _now_tpe()
    last = now.replace(minute=(now.minute // 30) * 30, second=0, microsecond=0)
    nxt = last + timedelta(minutes=30)
    return {
        "updated_at": last.strftime("%Y-%m-%d %H:%M"),
        "next_update": nxt.strftime("%H:%M"),
        "ai_brief": {
            "headline": "🔴 鋰 / NAND 雙線爆衝 · 供應鏈短期承壓",
            "summary": ("鋰價單月狂漲 18.3%(碳酸鋰供需失衡),NAND 漲 12.5%(三星廠維護延長)。"
                        " 銅、原油持續吃緊,鋼鐵唯一持平。本週重點是 Q4 採購合約鎖價窗口。"),
            "top_threat": "鋰價失控(碳酸鋰 +18.3% · 電池模組成本面臨重估)",
            "powered_by": "Claude Sonnet 4.5 · 每 30 分鐘自動更新",
        },
        "materials": [
            {"name": m, **MATERIAL_INSIGHTS[m]} for m in MATERIALS
        ],
    }


# ---------- HTML rendering ----------

def _sparkline_svg(values, color):
    if not values:
        return ""
    w, h = 120, 32
    n = len(values)
    vmin, vmax = min(values), max(values)
    rng = max(vmax - vmin, 1)
    pts = " ".join(
        f"{i * w / max(n - 1, 1):.1f},{h - (v - vmin) / rng * h:.1f}"
        for i, v in enumerate(values)
    )
    return (f'<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
            f'<polyline fill="none" stroke="{color}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" points="{pts}"/>'
            f'</svg>')


_LEVEL_META = {
    "HIGH": ("rose",    "🔴", "高風險", "#e11d48"),
    "MID":  ("amber",   "🟡", "中風險", "#d97706"),
    "LOW":  ("emerald", "🟢", "低風險", "#059669"),
}


def _render_card(m):
    c, emoji, label, hex_color = _LEVEL_META[m["level"]]
    delta = m["pct_change"]
    delta_str = f"{'+' if delta > 0 else ''}{delta:.1f}%"
    delta_color = hex_color
    spark = _sparkline_svg(m["sparkline"], hex_color)
    return f"""
    <article class="bg-white rounded-2xl p-6 ring-1 ring-slate-200 shadow-sm hover:shadow-md hover:ring-violet-200 transition-all flex flex-col gap-4">
      <div class="flex items-center justify-between">
        <h3 class="text-2xl font-bold text-slate-900">{m["name"]}</h3>
        <span class="text-xs font-semibold px-2.5 py-1 rounded-full ring-1 bg-{c}-50 text-{c}-700 ring-{c}-200">
          {emoji} {label}
        </span>
      </div>
      <div class="flex items-end justify-between gap-3">
        <div class="text-3xl font-bold" style="color: {delta_color}">{delta_str}</div>
        <div class="opacity-80">{spark}</div>
      </div>
      <a href="{m["event_url"]}" target="_blank" rel="noopener noreferrer"
        class="text-sm text-slate-700 hover:text-violet-700 border-t border-slate-100 pt-3">
        📰 {m["recent_event"]} <span class="text-violet-500">↗</span>
      </a>
      <div class="rounded-xl bg-gradient-to-br from-violet-50 to-fuchsia-50 ring-1 ring-violet-100 px-4 py-3">
        <div class="text-[10px] font-bold tracking-[0.1em] uppercase text-violet-700 mb-2">✨ AI 分析</div>
        <p class="text-[13px] leading-relaxed text-slate-700">{m["ai_insight"]}</p>
      </div>
      <div class="rounded-xl bg-amber-50 ring-1 ring-amber-200 px-4 py-3">
        <div class="flex items-start gap-2">
          <span>💡</span>
          <p class="text-[13px] font-medium text-amber-900 leading-relaxed">{m["action"]}</p>
        </div>
      </div>
    </article>
    """


def get_dashboard_html() -> str:
    d = get_dashboard()
    brief = d["ai_brief"]
    cards = "".join(_render_card(m) for m in d["materials"])
    return f"""<!DOCTYPE html>
<html lang=\"zh-TW\">
<head>
<meta charset=\"UTF-8\">
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<title>原物料風險戰情室 · Agent Factory</title>
<script src=\"https://cdn.tailwindcss.com\"></script>
<style>
  body {{ font-family: ui-sans-serif, system-ui, -apple-system, \"Noto Sans TC\", sans-serif; }}
  @keyframes pulse-dot {{ 0%, 100% {{ opacity: 1; transform: scale(1); }} 50% {{ opacity: 0.5; transform: scale(1.4); }} }}
  .live-dot {{ animation: pulse-dot 2s ease-in-out infinite; }}
</style>
</head>
<body class=\"min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50/40\">
<main class=\"max-w-6xl mx-auto px-6 py-12 lg:py-16\">

  <header class=\"mb-10\">
    <div class=\"flex items-center gap-2 mb-3\">
      <span class=\"inline-block w-2 h-2 rounded-full bg-emerald-500 live-dot\"></span>
      <span class=\"text-[11px] font-bold tracking-[0.15em] uppercase text-emerald-600\">Live · {d["updated_at"]}</span>
    </div>
    <h1 class=\"text-4xl lg:text-5xl font-bold text-slate-900 tracking-tight mb-2\">原物料風險戰情室</h1>
    <p class=\"text-slate-600\">Agent Factory 自動產出 · 5 種採購原料即時風險監控</p>
    <p class=\"text-xs text-slate-400 mt-2\">🕒 上次更新 {d["updated_at"]} · 下次更新 {d["next_update"]} · Cron 每 30 分鐘 · 台北時區</p>
  </header>

  <section class=\"relative overflow-hidden rounded-2xl bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-600 text-white shadow-xl shadow-violet-500/20 mb-12\">
    <div class=\"absolute -top-24 -right-24 w-72 h-72 bg-white/10 rounded-full blur-3xl pointer-events-none\"></div>
    <div class=\"absolute -bottom-32 -left-16 w-72 h-72 bg-fuchsia-400/20 rounded-full blur-3xl pointer-events-none\"></div>
    <div class=\"relative p-8 lg:p-10\">
      <div class=\"flex items-center gap-2 mb-5\">
        <span class=\"text-2xl\">✨</span>
        <span class=\"text-[11px] font-bold tracking-[0.15em] uppercase text-white/85\">AI 戰情摘要 · {brief["powered_by"]}</span>
      </div>
      <h2 class=\"text-2xl lg:text-3xl font-bold leading-snug mb-4\">{brief["headline"]}</h2>
      <p class=\"text-base lg:text-lg leading-relaxed text-white/90 mb-6 max-w-4xl\">{brief["summary"]}</p>
      <div class=\"inline-flex items-center gap-3 rounded-lg bg-white/10 backdrop-blur-sm px-4 py-3 ring-1 ring-white/20\">
        <span class=\"text-rose-200 font-semibold text-sm\">⚠️ 今日最大威脅</span>
        <span class=\"text-white text-sm\">{brief["top_threat"]}</span>
      </div>
    </div>
  </section>

  <div class=\"flex items-end justify-between mb-6\">
    <h2 class=\"text-xl font-bold text-slate-900\">5 種採購原料即時風險</h2>
    <span class=\"text-xs text-slate-500\">每 30 分鐘 Cron 自動更新</span>
  </div>

  <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5\">
    {cards}
  </div>

  <footer class=\"mt-16 pt-6 border-t border-slate-200 text-center text-xs text-slate-400\">
    Agent Factory · 一句話 → 5 個 agent 接力 → 上線的 AI 產品<br>
    Powered by Claude Sonnet 4.5
  </footer>
</main>
</body>
</html>"""
''',
        "notifier.py": '''"""Push to Slack #procurement-alerts + Telegram fallback."""
from __future__ import annotations
import os
import httpx
from risk_scorer import RiskSnapshot


def push_alerts(snap: RiskSnapshot) -> None:
    msg = _format(snap)
    _push_slack(msg)
    _push_telegram(msg)


def _format(snap: RiskSnapshot) -> str:
    lines = ["🚨 原物料風險警報"]
    for d in snap.deltas:
        arrow = "↗" if d.pct_change > 0 else "↘"
        lines.append(f"• {d.material}  {d.old_level} → {d.new_level}  {arrow}{abs(d.pct_change):.1f}%")
    return "\\n".join(lines)


def _push_slack(text: str) -> None:
    url = os.getenv("SLACK_WEBHOOK_URL")
    if not url:
        return
    httpx.post(url, json={"text": text}, timeout=10.0)


def _push_telegram(text: str) -> None:
    token = os.getenv("TG_BOT_TOKEN")
    chat_id = os.getenv("TG_CHAT_ID")
    if not (token and chat_id):
        return
    httpx.post(
        f"https://api.telegram.org/bot{token}/sendMessage",
        json={"chat_id": chat_id, "text": text},
        timeout=10.0,
    )
''',
        "materials.py": '''"""The 5 raw materials we track for ASUS procurement."""
MATERIALS = ["NAND", "銅", "鋼鐵", "鋰", "原油"]
''',
        "Dockerfile": '''FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
''',
        "requirements.txt": "fastapi==0.115.0\nuvicorn==0.32.0\napscheduler==3.10.4\nhttpx==0.27.2\nanthropic>=0.100.0\n",
    },

    # --- Fallback (monitoring agent, like the original匯率 demo) ---
    "_default": {
        "main.py": '''"""Auto-generated by Agent Factory."""
from fastapi import FastAPI
from apscheduler.schedulers.background import BackgroundScheduler
from fetcher import fetch
from notifier import notify

app = FastAPI()
sched = BackgroundScheduler()


@sched.scheduled_job("interval", minutes=5)
def check() -> None:
    data = fetch()
    if data.get("alert"):
        notify(data["message"])


@app.on_event("startup")
def _start() -> None:
    sched.start()
''',
        "fetcher.py": '''"""Fetch data source. Replace URL with your target."""
import httpx


def fetch() -> dict:
    r = httpx.get("https://api.example.com/data")
    return r.json()
''',
        "notifier.py": '''"""Push to Telegram."""
import os
import httpx


def notify(msg: str) -> None:
    token = os.getenv("TG_TOKEN")
    chat_id = os.getenv("TG_CHAT_ID")
    if not token:
        return
    httpx.post(
        f"https://api.telegram.org/bot{token}/sendMessage",
        json={"chat_id": chat_id, "text": msg},
    )
''',
        "Dockerfile": '''FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
''',
        "requirements.txt": "fastapi==0.115.0\nuvicorn==0.32.0\napscheduler==3.10.4\nhttpx==0.27.2\n",
    },
}


# ============ HELPERS ============

# D2.4 demo trigger — only used in mock mode, so we can show the self-fix loop
# without needing real API. Any of these keywords in user_request will cause
# Builder iteration 0 to inject a syntax error into main.py; iteration 1 fixes it.
_INJECT_FAILURE_KEYWORDS = ["故意", "intentional", "error demo", "import 錯誤", "壞 prompt"]


def _select_files_bundle(subcategory: str) -> dict[str, str]:
    """Pick the right mock bundle based on the PRD subcategory."""
    return MOCK_FILES_BY_CATEGORY.get(subcategory, MOCK_FILES_BY_CATEGORY["_default"])


def _should_inject_failure(user_request: str, iteration: int) -> bool:
    if iteration != 0:
        return False
    return any(k in user_request for k in _INJECT_FAILURE_KEYWORDS)


def _summarize_tool_call(name: str, inp: dict) -> str:
    if name == "write_file":
        return f"write_file {inp.get('path', '?')}"
    if name == "read_file":
        return f"read_file {inp.get('path', '?')}"
    if name == "list_dir":
        return f"list_dir {inp.get('path', '.')}"
    if name == "run_command":
        cmd = inp.get("cmd", "")
        return f"run_command {cmd[:60]}"
    if name == "submit_done":
        return "submit_done"
    return name


def _read_sandbox_files(job_id: str) -> dict[str, str]:
    """Read every text file in generated/{job_id}/ recursively (after agent loop)."""
    root = Path("generated") / job_id
    if not root.exists():
        return {}
    out: dict[str, str] = {}
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        try:
            out[rel] = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
    return out


# ============ MOCK AGENT LOOP ============

def _fallback_file_content(state: FactoryState, name: str) -> str:
    prd = state.get("prd", {}) or {}
    analysis = state.get("analysis", {}) or {}
    criteria = state.get("acceptance_criteria", []) or []

    if name.lower().endswith("readme.md"):
        workflow = "\n".join(f"{i + 1}. {step}" for i, step in enumerate(analysis.get("workflow", []) or []))
        checklist = "\n".join(f"- {item}" for item in criteria)
        return (
            f"# {prd.get('name_tc', 'Agent Factory 產物')}\n\n"
            f"{prd.get('summary', '自動產生的業務工具。')}\n\n"
            "## 目標使用者\n"
            f"{analysis.get('audience', '一般使用者')}\n\n"
            "## 使用流程\n"
            f"{workflow or '1. 啟動服務\n2. 查看首頁或 dashboard\n3. 依提示設定資料來源'}\n\n"
            "## 驗收標準\n"
            f"{checklist or '- 首頁可 demo\n- 有範例資料\n- 有中文錯誤提示'}\n"
        )

    if name == ".env.example":
        return (
            "# Agent Factory generated config\n"
            "PORT=8000\n"
            "SLACK_WEBHOOK_URL=\n"
            "TG_BOT_TOKEN=\n"
            "TG_CHAT_ID=\n"
        )

    if name.lower().endswith("sample_data.json"):
        payload = {
            "app": prd.get("name_tc", "demo"),
            "subcategory": prd.get("subcategory", "_default"),
            "items": [
                {"name": "示範項目 A", "status": "正常", "note": "可 demo 的範例資料"},
                {"name": "示範項目 B", "status": "注意", "note": "用於驗證 UI 與 fallback"},
            ],
        }
        return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"

    return f"# auto-generated stub for {name}\n"


def _builder_mock(state: FactoryState, job_id: str, iteration: int, log: list[str]) -> dict[str, str]:
    """Simulate the agent loop in mock mode: real tool calls via tools.py,
    but file contents come from MOCK_FILES_BY_CATEGORY."""
    subcat = state["prd"].get("subcategory", "_default")
    bundle = _select_files_bundle(subcat)
    file_plan = state["design"].get("file_plan") or list(bundle.keys())

    user_request = state.get("user_request", "")
    inject_fail = _should_inject_failure(user_request, iteration)

    written: dict[str, str] = {}
    tool_calls = 0

    for name in file_plan:
        content = bundle.get(name, _fallback_file_content(state, name))
        if inject_fail and name == "main.py":
            content = content + "\n# D2.4 demo: intentional syntax error\nthis is not valid python at all !!!\n"

        result = write_file(job_id, name, content)
        tool_calls += 1
        if result["ok"]:
            log.append(f"  [tool] write_file {name} ✓")
            written[name] = content
        else:
            log.append(f"  [tool] write_file {name} ✗ ({result['error']})")

    # one verification command — exercise run_command for real
    verify = run_command(job_id, "python --version")
    tool_calls += 1
    check = "✓" if verify["ok"] else "✗"
    log.append(f"  [tool] run_command python --version {check}")

    # signal done
    tool_calls += 1
    log.append(f"  [tool] submit_done ✓")

    log.append(f"✓ Builder: 寫完 {len(written)} 個檔案 · {tool_calls} 次工具呼叫")
    return written


# ============ REAL ONE-SHOT BUILDER ============
# 為什麼不用 agent loop?
#   主辦 Azure endpoint 限制 2000 input tokens / 60 秒(TPM)。
#   原本 agent loop 每次 tool_call 都把對話歷史整包傳回去 → 第 4-5 次就爆 input quota。
#   改成「一次 Claude call · 輸出所有檔案的 JSON」 → 單 call ~1500 input 不撞牆。
#   故事還是 5-agent · Builder 仍真用 Claude · 只是寫法 batch 不是 streaming。

BUILDER_ONESHOT_SYSTEM = """你是 Agent Factory 的 Builder。給你 PRD + Design + 檔案清單,
你一次輸出所有檔案的完整內容,以 JSON 格式。

嚴格格式(只回 JSON · 不要任何前言 / 解釋 / markdown fence):
{
  "files": [
    {"path": "main.py", "content": "完整檔案內容..."},
    {"path": "fetcher.py", "content": "..."}
  ]
}

⚠️ **JSON string 內 backslash escape 規則(必須遵守 · 違反整個 JSON parse 失敗)**:
JSON string 內任何 `\\` 後面如果不是 `n / t / r / " / \\ / / / b / f / u` 都必須 double-escape 成 `\\\\`。
常見錯例 + 正確寫法:
- Python regex `\\d+`        → JSON 寫成 `"\\\\d+"`
- Python regex `\\s*`        → `"\\\\s*"`
- Python regex `[\\s\\S]`    → `"[\\\\s\\\\S]"`
- Windows path `C:\\Users`   → `"C:\\\\Users"`
- LaTeX `\\alpha`            → `"\\\\alpha"`
規則簡單:**寫 content 字串時 · 任何單一 `\\` 全部變成 `\\\\`** · 除非後面正好是 `n / t / r / " / \\ / b / f / u`(這 9 個是 JSON 合法 escape)。

規則:
- 每個檔案完整可跑 · 不要 TODO · 不要省略
- 嚴格遵守 design.file_plan 列表 · 不要少寫任何檔案
- 必須滿足 Analyst brief 與 acceptance criteria,不能只做表面 demo
- README.md 要清楚說明目標使用者、設定、部署、限制與 demo 流程
- sample_data.json 要能支撐首頁/測試/fallback,不得空陣列
- Python 用 type hints · 不要 import 不存在的套件
- TypeScript/JavaScript 確保語法正確
- 不要解釋 · 只回完整 JSON

⚠️ 重要:Web 服務必須包含 HTML 首頁
如果產出物是 FastAPI / Flask / Next.js 等 web 服務,main.py(或對應的 app/page.tsx)**必須**:
1. 有一個根路由 `@app.get("/", response_class=HTMLResponse)`(FastAPI)或 page.tsx(Next.js)
2. 回傳完整 HTML(內嵌 Tailwind CDN: <script src="https://cdn.tailwindcss.com"></script>)
3. HTML 有 hero banner + 卡片式呈現主要資料 + 紫色強調色 + 圓角 + 陰影
4. JavaScript fetch /api/dashboard(或對應 JSON endpoint)並渲染畫面
5. setInterval 每 30 秒自動 refresh 資料

範例骨架(自行依需求改):
```python
from fastapi.responses import HTMLResponse

@app.get("/", response_class=HTMLResponse)
async def root() -> HTMLResponse:
    return HTMLResponse('''<!DOCTYPE html>
<html><head><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-slate-50">
  <main class="max-w-6xl mx-auto p-8">
    <h1 class="text-4xl font-bold">...</h1>
    <div id="data">載入中...</div>
  </main>
  <script>
    async function load() {
      const r = await fetch("/api/dashboard");
      // render r.json() into the page
    }
    load(); setInterval(load, 30000);
  </script>
</body></html>''')
```

JSON-only API 服務(無 HTML 首頁)會**讓終端用戶看到 404 · 不可接受**。

⚠️ 資料新鮮度 · 必須遵守(這不是 demo · 是實戰):
- **絕對禁止 hardcode 日期字串**(例如 `"updatedAt": "2024-12-15T08:00:00+08:00"`)· 違規 = 整個 PR 失敗
- 所有 `updatedAt` / `pubDate` / `time` / `lastUpdated` 欄位:
  - 第一首選:從真實來源抓(Google News RSS / 官方 API / yfinance)· 用 RSS `<pubDate>` 解出來
  - 第二選:用 `new Date().toISOString()` (TS) 或 `datetime.utcnow().isoformat()` (Python) 生「現在」
  - **不可以**寫死任何日期 · 連 fallback / sample / mock 都不行
- `sample_data.json` 裡的事件 `updatedAt` 必須用 placeholder(例如 `"__NOW__"`),由 server 端 runtime 替換成 `new Date()` · 或乾脆不寫死 events,讓 scraper 完全生成
- **競品爬蟲**(war_room):design 裡列出的每一家競品都要有自己的 scraper · 不能只做兩家把另外三家留 sample data
- Google News RSS query 用 `encodeURIComponent('競品名 中文關鍵字')` · 解析 `<item><pubDate>` 把日期帶進來
- 「每次請求都重新抓」的設定要放對地方(下面 Next.js 段詳述)· 不要 SSG 靜態化

⚠️ TypeScript / Next.js · 必須遵守(防止 build error):
- `tsconfig.json` 的 `target` **必須是 `"es2020"` 或更新**(`"es5"` 不可 · `regex flag /s` /`/u` / `/d` 都會 build 失敗)
- `lib`: `["dom", "dom.iterable", "esnext"]` 完整
- `moduleResolution`: `"bundler"` 或 `"node"`
- 避免使用 `/regex/s` 這種需要 ES2018+ 的 flag · 改用 `[\\s\\S]` 取代 `.`(更通用)
- Next.js 14 使用 App Router · `app/page.tsx` + `app/layout.tsx` 都要有 · `app/page.tsx` 是首頁
- 任何外部 npm 套件都要在 `package.json` 的 `dependencies` 列出 · 不要 import 沒裝的
- **跨檔共享的 TypeScript type / interface 必須 `export`** · 任何 `import { X } from "./other"` 之前 · 確認 other.ts 真的 `export interface X` 或 `export type X`
- **shared types 抽到 `scrapers/types.ts` 或 `lib/types.ts`**(不要把 type 塞在 acer.ts 然後 dell.ts 互 import · 容易漏 export)
- 所有 `interface` 跟 `type` 預設加 `export` · 即使該檔現在沒被別檔 import(零成本 · 但避免之後加新檔 import 時忘記回去改)
- **React / Next.js page 必須對 sample_data 全部 case(含 test-error / test-variant 缺欄位的 case)都不能 crash**
  - 訪問可能 undefined 的物件屬性 · 用 optional chaining(`comp?.opportunities`)
  - 對可能 null/undefined 的 array 用 nullish coalescing(`(comp.opportunities ?? []).map(...)`)
  - 對可能缺欄位的數字加預設(`comp.riskScore ?? 0`)
  - 用 `try/catch` 包 `parseISO` / `JSON.parse` 之類會 throw 的呼叫
  - 心法:**sample_data 為了測邊界故意有缺欄位 case** · page 看到爛資料應 graceful degrade 顯示「資料不完整」· 不是整個 React 樹炸掉給 user 看「Application error」
- If `app/page.tsx` starts with `"use client"`, do not export Next route config from that file.
  In client components, never include `export const revalidate`, `export const dynamic`,
  `export const fetchCache`, or `export const runtime`.
- For client pages that fetch with `useEffect`, use `fetch(..., { cache: "no-store" })`
  instead of `export const revalidate = 0`.

⚠️ Next.js Route Segment Config · 放對地方(這條搞錯整個 build 會掛):
- `export const revalidate` / `export const dynamic` 是 **Route Segment Config** · 只能放在:
  1. **Server Components**(沒有 `"use client"` 的 `page.tsx` / `layout.tsx`)
  2. **Route Handlers**(`app/api/*/route.ts`)
- **絕對不可以**放在 `"use client"` 的檔案 · 否則 Next.js 會把整個 export map 當成 revalidate 值 · 報錯
  `Invalid revalidate value "[object Object]" on "/" · must be a non-negative number or "false"`
- 如果 `app/page.tsx` 因為要用 `useState` / `useEffect` 必須是 `"use client"`:
  - **不要**在 page.tsx 匯出 `revalidate` / `dynamic`
  - 客戶端不快取的做法:`fetch('/api/...', { cache: 'no-store' })` · 或 `fetch('/api/...?t=' + Date.now())`
  - 把 `revalidate = 0` 放到 `app/api/*/route.ts` 那層(server 端 cache 控制)
- 如果是純展示頁(不用 client hooks)· 推薦的 server-side fresh fetch:
  - `app/page.tsx` **不要**寫 `"use client"`
  - 頂部 `export const revalidate = 0; export const dynamic = "force-dynamic";`
  - 用 `async function Page()` 直接 await fetch
  - `app/api/*/route.ts` 也要 `export const revalidate = 0;` + 回 header `Cache-Control: no-store`

⚠️ 中文為主英文輔助 · 必須遵守:
- 使用者是台灣採購人員 + 評審 + 公司同事 · **全部 UI 標題 / banner / 卡片標題 / 按鈕 / 提示文字 / footer 都用繁體中文**
- 新聞 fallback / 模擬資料 / 警報訊息 / log 給人看的部分 → 中文
- 第三方 API 查詢字串(例如 Google News RSS 的 q 參數)→ 使用中文關鍵字 · 配合 `urllib.parse.quote` 做 URL encode
- 英文只在技術命名(class name / function name / API path / 程式碼註解)+ 商品縮寫(BRENT / WTI)時保留
- 雙語標示優先(例如「布蘭特 BRENT」「銅 CU」)讓兩邊都看得懂

⚠️ ASUS 角度 · 商業內容必須從 ASUS 出發:
- 使用者是 **ASUS 採購部** · Factory 產出的所有內容(競品分析 / 原料風險 / 供應商追蹤 / 戰略建議)都以 ASUS 為「**我方**」
- **競品**(war_room):是 ASUS 的實際對手 = **ACER · MSI · HP · DELL · Lenovo**(筆電/PC 領域)
- **建議行動**:從 ASUS 角度寫(例:「加速 ROG 第三季鋪貨」· 因為 ROG 是 ASUS 電競品牌;不要寫「加速 X 品牌鋪貨」這種抽象話)
- **AI 分析**:對標 ASUS 產品線(ROG / ZenBook / ProArt / VivoBook / TUF Gaming)
- **原料風險**(raw_material_risk):衝擊要寫「對 ASUS 採購團隊」· 不要寫「對市場」
- **內部簽核 / KPI 簡報**:符合 ASUS 內部組織(採購單 → 主管 → 採購副總)
- **個人類產品**(family_photo / personal_budget)不適用此規則 · 維持中性敘事"""


# === Subcategory-specific spec · 只在符合的 subcategory 才注入 user_msg ===
# (放這裡 · 不放 BUILDER_ONESHOT_SYSTEM · 避免 system prompt 對所有 category 都太肥)
DESKTOP_DIFF_SPEC = """
⚠️ **desktop_app · excel_diff / multi_format_diff 專屬規格**(這個 prd 是這類 · 必須做到):

UI:必用 customtkinter(或 ttkbootstrap)· 禁裸 tkinter · dark mode · 1100x720+ · 主標題 banner · 拖放區(tkinterdnd2)· 進度條 · 結果用 ctk.CTkTabview 每 sheet 1 tab · 中文 label + emoji icon。

功能:支援 .xlsx/.xls/.csv(auto-detect 編碼)· auto-detect 主鍵欄 + 下拉可改 · 正規化比較(strip / 數字 / 日期 / unicode NFC)· 顏色 diff(綠新 / 紅刪 / 黃改)· 匯出 3 種(標紅 .xlsx + 摘要 .xlsx + PDF reportlab)。sample_data 4 對:正常 / 邊界(空 sheet)/ 錯誤(主鍵缺)/ 多變化(欄位順序+sheet 數不同)。

錯誤:user 觸發點全 try/except · 抓 KeyError / FileNotFoundError / PermissionError / UnicodeDecodeError / ValueError / IndexError · 用 messagebox.showerror 中文友善訊息(不是 raise 給 console)。

CLI:`if __name__ == "__main__"` + argparse 支援 --selftest · selftest 跑完整 headless 流程 · 成功 print SELFTEST_OK exit 0 · 失敗 print SELFTEST_FAIL exit 1。

PyInstaller:--onefile · hiddenimports 列 customtkinter / tkinterdnd2 / openpyxl / pandas / reportlab · datas 包 sample_data · console=False。

requirements.txt 必含:customtkinter>=5.2, tkinterdnd2>=0.4, openpyxl>=3.1, pandas>=2.0, reportlab>=4.0, pyinstaller>=6.0。

(multi_format_diff 額外:加 pdfplumber>=0.10 + python-docx>=1.0 · loaders 依副檔名分流 · 正規化成共通 dict 再比。)
""".strip()


def _builder_real(state: FactoryState, job_id: str, iteration: int, log: list[str]) -> dict[str, str]:
    """One-shot Claude call · 輸出所有檔案的 JSON · 寫進 sandbox。

    跟原本的 agent loop 比較:
      - input 不會累積 → 撐得住主辦 endpoint 的 TPM 限制
      - 單一 call 完成 → 30-60 秒
      - 仍然真用 Claude 寫 code
    """
    prd = state["prd"]
    design = state["design"]
    analysis = state.get("analysis", {}) or {}
    acceptance_criteria = state.get("acceptance_criteria", []) or []
    file_plan = design.get("file_plan", [])
    lessons_context = format_lessons_for_prompt(state)

    # 對 desktop_app diff 類別 · 在 user_msg 注入專屬規格(避免 system prompt 對其他 category 也肥)
    subcat = prd.get("subcategory", "")
    spec_block = (DESKTOP_DIFF_SPEC + "\n\n") if subcat in {"excel_diff", "multi_format_diff"} else ""

    user_msg = (
        f"{spec_block}"
        f"PRD:\n{json.dumps(prd, ensure_ascii=False, indent=2)}\n\n"
        f"Design:\n{json.dumps(design, ensure_ascii=False, indent=2)}\n\n"
        f"Analyst brief:\n{json.dumps(analysis, ensure_ascii=False, indent=2)}\n\n"
        f"Acceptance criteria:\n{json.dumps(acceptance_criteria, ensure_ascii=False, indent=2)}\n\n"
        f"file_plan(這 {len(file_plan)} 個檔案必須全部產出):\n"
        f"{json.dumps(file_plan, ensure_ascii=False)}\n\n"
        f"輸出 JSON,包含所有檔案的完整內容。"
    )

    if lessons_context:
        lesson_count = sum(1 for line in lessons_context.splitlines() if line.startswith("- "))
        log.append(f"  Memory: loaded {lesson_count} relevant lesson(s)")
        user_msg += f"\n\n{lessons_context}"

    if iteration > 0:
        prev_errors = state.get("test_results", {}).get("errors", [])
        if prev_errors:
            errors_str = "\n".join(prev_errors)
            user_msg += (
                f"\n\n⚠️ 上一次測試失敗 (iteration {iteration - 1}),錯誤:\n"
                f"{errors_str}\n\n請修正後重寫完整 JSON。"
            )

    # Kimi 路徑 TPM 35K(寬鬆 17 倍)· 不需冷卻 · 直接打
    # Claude 路徑沿用 65s 冷卻(Azure Anthropic 限 2000 TPM)
    import os as _os
    if _os.getenv("USE_KIMI_FOR_BUILDER", "false").lower() == "true":
        log.append("  ⚡ Kimi-K2.5 路徑(35K TPM)· 跳過 65s 冷卻 · 直接打")
    else:
        log.append(f"  ⏳ Claude 路徑 · 給 Azure TPM 視窗冷卻 {_BUILDER_STARTUP_DELAY:.0f}s · 避免 2000 tokens/60s 上限...")
        time.sleep(_BUILDER_STARTUP_DELAY)

    log.append(f"  📝 Builder 一次 call 輸出 {len(file_plan)} 個檔案...")
    # 把品質憲法注入到 system prompt · 所有產品都套同一份基線
    system_prompt = f"{BUILDER_ONESHOT_SYSTEM}\n\n{get_constitution()}"
    # 走 router · USE_KIMI_FOR_BUILDER=true → Kimi-K2.5 · 否則 Claude sonnet
    # Kimi 路徑能拿 35K TPM(vs Claude 2K)· 省 Claude 預算 + 不必 65s 冷卻
    resp = create_builder_message(
        log=log,
        model=MODELS["sonnet"],
        max_tokens=32000,  # 拉到上限 · war_room 12 檔需要更多空間
        system=system_prompt,
        messages=[{"role": "user", "content": user_msg}],
    )

    text = "".join(b.text for b in resp.content if hasattr(b, "text"))
    stop_reason = getattr(resp, "stop_reason", "?")
    usage_info = getattr(resp, "usage", None)
    in_tok_used = getattr(usage_info, "input_tokens", "?") if usage_info else "?"
    out_tok_used = getattr(usage_info, "output_tokens", "?") if usage_info else "?"

    # Empty response guard:Azure 端有時候因 rate limit / 內部問題回空 body
    # 加詳細診斷訊息給 Lara 看 · 不要只 raise 不知道原因
    if not text.strip():
        log.append(f"  ✗ Builder 回了空 response · stop_reason={stop_reason} · input={in_tok_used} / output={out_tok_used} tokens")
        log.append(f"     可能原因:Azure rate limit / token budget / endpoint 內部錯誤")
        log.append(f"     資訊:system prompt {len(system_prompt):,} chars · user msg {len(user_msg):,} chars")
        raise ValueError(
            f"Builder LLM 回空 response(stop_reason={stop_reason}, in={in_tok_used}/out={out_tok_used})· "
            f"可能 Azure rate-limited 或 system prompt 太大({len(system_prompt):,} chars)· "
            "可試 USE_KIMI_FOR_BUILDER=true 換 provider · 或縮 acceptance_criteria 條數"
        )

    if stop_reason == "max_tokens":
        log.append(f"  ⚠️ Claude 回應被 max_tokens 截斷 (回了 {len(text)} chars · stop_reason={stop_reason})")

    # Strip markdown fences if Claude included them
    text = re.sub(r"^```(?:json)?\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text)

    data = _tolerant_json_loads(text, log)
    if data is None:
        raise json.JSONDecodeError("Builder oneshot: even tolerant parse failed", text, 0)

    files_list = data.get("files", [])
    if not files_list:
        log.append("  ✗ Claude 回的 JSON 沒有 files 欄位")
        raise ValueError("Builder oneshot: JSON missing 'files' key")

    written: dict[str, str] = {}
    for entry in files_list:
        path = entry.get("path")
        content = entry.get("content")
        if not path or content is None:
            continue
        result = write_file(job_id, path, content)
        if result["ok"]:
            log.append(f"  [tool] write_file {path} ✓")
            written[path] = content
        else:
            log.append(f"  [tool] write_file {path} ✗ ({result['error']})")

    usage = getattr(resp, "usage", None)
    in_tok = getattr(usage, "input_tokens", 0) if usage else 0
    out_tok = getattr(usage, "output_tokens", 0) if usage else 0
    log.append(
        f"✓ Builder: 寫完 {len(written)} 個檔案 · "
        f"1 次 Claude call (input {in_tok} / output {out_tok} tokens)"
    )

    # L3 兩層 critique
    # Layer A · deterministic rule-based(掃 regex / 找關鍵字)
    rule_critique = _critique_built_files(written, prd, design)

    # Layer B · agentic LLM critique(sonnet review code digest · 找 deeper 設計問題)
    acceptance = state.get("acceptance_criteria", []) or []
    llm_critique = _llm_critique_built_files(written, prd, acceptance, log)

    # 合併兩層 + 計算最終分數(取較低)
    final_score = min(rule_critique["score"], llm_critique.get("score", 100))
    all_issues = rule_critique["issues"] + llm_critique.get("issues", [])
    critique = {
        "score": final_score,
        "rule_score": rule_critique["score"],
        "llm_score": llm_critique.get("score", None),
        "issues": all_issues,
        "rule_checks": rule_critique["checks"],
        "llm_review": llm_critique.get("review", ""),
    }
    state["builder_critique"] = critique
    if all_issues:
        log.append(f"  ⚠️ Builder L3 critique 找到 {len(all_issues)} 條(rule {rule_critique['score']}/100 · LLM {llm_critique.get('score', 'n/a')}/100):")
        for issue in all_issues[:5]:
            log.append(f"     · {issue}")
        if len(all_issues) > 5:
            log.append(f"     · ... 還有 {len(all_issues) - 5} 條")
    else:
        log.append(f"  ✓ Builder L3 critique 過關 · rule {rule_critique['score']}/100 · LLM {llm_critique.get('score', 'n/a')}/100")

    return written


# === L3 LLM critique ===

_L3_LLM_DELAY = 65.0  # Azure TPM window cooldown 一致

L3_LLM_SYSTEM = """你是 Agent Factory 的 L3 Builder Code Reviewer。

角色:看 Builder 剛寫的 code · 對照 acceptance_criteria + 品質憲法 · 找出**結構性 / 設計性**的問題(不是 lint 級別 · rule-based 那層已經處理)。

關注:
- 主流程是否真的能完成 user 想做的事?(不是 stub / 不是 TODO)
- UI 是否實作了關鍵互動?(按鈕對應的 handler 真有實作?)
- 多檔案是否真互相串接?(import 跟實際呼叫對得起來?)
- 邊界 case 真的 catch 了 還是只有寫 try/except 但內部還是 raise?
- sample_data 真的能跑出有意義結果還是只是 placeholder?

評分 1-100:
- 90-100:扎實 · ship 沒問題
- 70-89:能 demo · 但有 1-2 個明顯缺陷
- 50-69:有明顯問題 · 評審追問會穿幫
- < 50:不行 · 必須重做

輸出嚴格 JSON:
{
  "score": 0-100 數字,
  "issues": ["問題 1 描述", "問題 2 描述", ...],
  "review": "1-2 段整體評論"
}"""


def _llm_critique_built_files(
    files: dict[str, str],
    prd: dict,
    acceptance: list[str],
    log: list[str],
) -> dict:
    """L3 agentic critique · sonnet 看 file digest · 抓設計 / 結構問題。

    REAL 模式等 65s 冷卻 · MOCK 模式跳過回 {}
    Failsafe:LLM 掛了不阻擋 · 回空 dict。
    """
    if is_mock():
        return {}

    log.append(f"  ⏳ L3 LLM critique 等 Azure TPM 視窗 {_L3_LLM_DELAY:.0f}s...")
    time.sleep(_L3_LLM_DELAY)

    # File digest:每檔頭 30 行 + 大小 · 控制在 ~6KB 內
    digest_parts = []
    for name, content in list(files.items())[:15]:  # 最多 15 檔
        head = "\n".join(content.splitlines()[:30])
        digest_parts.append(f"=== {name} ({len(content)} bytes) ===\n{head}")
    digest = "\n\n".join(digest_parts)
    if len(digest) > 8000:
        digest = digest[:8000] + "\n... (截斷)"

    acceptance_str = "\n".join(f"- {a}" for a in acceptance[:20])
    user_msg = (
        f"產品類別: {prd.get('subcategory')} ({prd.get('agent_type')})\n"
        f"產品目標: {prd.get('summary')}\n\n"
        f"關鍵 acceptance criteria:\n{acceptance_str}\n\n"
        f"Builder 寫的 file digest(每檔頭 30 行):\n\n{digest}\n\n"
        f"請 review · 重點看主流程實作 / 多檔案互相串接 / 邊界 case 是否真 catch / sample_data 真實性 · 輸出 JSON。"
    )

    try:
        result = call_llm_json(
            system=L3_LLM_SYSTEM,
            user=user_msg,
            model="sonnet",
            max_tokens=2500,
            log=log,
        )
        score = result.get("score")
        if not isinstance(score, (int, float)):
            return {}
        issues = result.get("issues", [])
        if not isinstance(issues, list):
            issues = []
        issues = [str(x).strip() for x in issues if isinstance(x, str) and str(x).strip()][:6]
        return {
            "score": int(score),
            "issues": issues,
            "review": str(result.get("review", ""))[:500],
        }
    except Exception as e:
        log.append(f"  ⚠️ L3 LLM critique 失敗(failsafe · 不阻擋):{type(e).__name__}: {e}")
        return {}


def _tolerant_json_loads(text: str, log: list[str]) -> dict | None:
    r"""嘗試嚴格 json.loads · 失敗的話自動修「Kimi 寫 JSON 漏 escape」這類常見錯。

    修法:把所有不合法的 backslash escape(`\X` X 不是 valid JSON escape char)
    自動 double-escape。例如:
      "\d+"   → "\\d+"   (Python regex backslash)
      "C:\U"  → "C:\\U"  (Windows path)
    Returns:dict 成功 / None 失敗(caller 應 raise)。
    """
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        log.append(f"  ⚠️ JSON strict parse 失敗: {e.msg} @ char {e.pos} · 嘗試 tolerant 修復...")

    # 把不合法的 backslash 自動 escape 成 double · 保留合法的 \" \\ \/ \b \f \n \r \t \uXXXX
    fixed = re.sub(r'\\(?!["\\/bfnrtu])', r'\\\\', text)
    try:
        result = json.loads(fixed)
        log.append(f"  ✓ Tolerant parse 成功 · 自動修了 {(len(fixed) - len(text))} 個 backslash escape")
        return result
    except json.JSONDecodeError as e2:
        log.append(f"  ✗ Tolerant parse 也失敗: {e2.msg} @ char {e2.pos}")
        log.append(f"     第一個 200 字: {text[:200]}")
        return None


def _critique_built_files(files: dict[str, str], prd: dict, design: dict) -> dict:
    """L3 · 對照憲法掃描 Builder 寫出來的檔案 · 找出明顯違反。

    Deterministic check · 0 token · 不觸發 retry(讓 L4 Tester runtime check 當 gate)。
    Returns: {"score": 0-100, "issues": [str], "checks": [...]}
    """
    agent_type = prd.get("agent_type", "")
    subcategory = prd.get("subcategory", "")
    is_personal = subcategory in {"family_photo", "personal_budget", "split_bill", "ecommerce"}

    issues: list[str] = []
    checks: list[dict] = []

    all_text = "\n".join(files.values())

    # 1. 禁硬編日期(任何 2024-/2025-/2026- 字串)· 但 .toISOString() / new Date() 自動產的不算
    bad_dates = re.findall(r"['\"](20\d{2}-\d{2}-\d{2})['\"]", all_text)
    real_bad = [d for d in bad_dates if not d.startswith("2099")]  # 2099 是常用 placeholder
    checks.append({"name": "禁硬編日期", "pass": not real_bad, "detail": f"找到 {len(real_bad)} 個硬編日期" if real_bad else "OK"})
    if real_bad:
        issues.append(f"違反「禁硬編日期」· 樣本:{real_bad[:3]}")

    # 2. sample_data.json 涵蓋多個 case
    sample_file = None
    for name, content in files.items():
        if name.endswith("sample_data.json"):
            sample_file = content
            break
    if sample_file:
        # 簡單啟發式:大於 1KB 通常代表有多 case
        size_ok = len(sample_file) > 500
        checks.append({"name": "sample_data 多 case", "pass": size_ok, "detail": f"{len(sample_file)} bytes"})
        if not size_ok:
            issues.append("sample_data.json < 500 bytes · 可能只 1 case · 憲法要求 4 case")

    # 3. UI 標準
    if agent_type == "desktop_app":
        has_modern_ui = any(
            kw in all_text
            for kw in ["customtkinter", "CustomTkinter", "ttkbootstrap", "ttk.Style"]
        )
        checks.append({"name": "Desktop UI 用 CustomTkinter/ttkbootstrap", "pass": has_modern_ui, "detail": "OK" if has_modern_ui else "用了裸 tkinter"})
        if not has_modern_ui:
            issues.append("Desktop 違反「禁裸 tkinter」· 應用 CustomTkinter 或 ttkbootstrap")
    elif agent_type in {"monitoring", "website", "automation"}:
        has_tailwind = "tailwindcss" in all_text.lower() or "tailwind" in all_text.lower()
        checks.append({"name": "Web UI 用 Tailwind", "pass": has_tailwind, "detail": "OK" if has_tailwind else "沒看到 Tailwind"})
        if not has_tailwind:
            issues.append("Web 違反「必用 Tailwind」")

    # 4. 可測試性
    if agent_type == "desktop_app":
        has_selftest = "--selftest" in all_text or "selftest" in all_text.lower()
        checks.append({"name": "Desktop 必有 --selftest", "pass": has_selftest, "detail": "OK" if has_selftest else "找不到 --selftest 入口"})
        if not has_selftest:
            issues.append("Desktop 違反「必有 --selftest CLI」· Tester L4 無法 runtime 驗")
    elif agent_type in {"monitoring", "website", "automation"}:
        has_health = "/api/health" in all_text or "/health" in all_text
        checks.append({"name": "Web 必有 /api/health", "pass": has_health, "detail": "OK" if has_health else "找不到 /api/health"})
        if not has_health:
            issues.append("Web 違反「必有 /api/health」")

    # 5. ASUS POV(僅 company 類)
    if not is_personal and subcategory not in ("", "_default"):
        has_asus = "ASUS" in all_text or "華碩" in all_text
        checks.append({"name": "company 類有 ASUS 字樣", "pass": has_asus, "detail": "OK" if has_asus else "整份產出找不到 ASUS"})
        if not has_asus:
            issues.append("Company 類違反「ASUS POV」· 沒出現 ASUS / 華碩")

    # 6. 錯誤捕捉(Python 主要檔案有 try/except)
    py_main_candidates = ["main.py", "app.py", "gui.py", "server.py", "diff_engine.py"]
    py_main_text = "\n".join(files[n] for n in py_main_candidates if n in files)
    if py_main_text:
        has_try = "try:" in py_main_text and "except" in py_main_text
        checks.append({"name": "Python 主流程有 try/except", "pass": has_try, "detail": "OK" if has_try else "沒看到錯誤捕捉"})
        if not has_try:
            issues.append("主流程沒 try/except · KeyError / FileNotFoundError 會直接炸給 user")

    # 計分
    total = len(checks) or 1
    passed = sum(1 for c in checks if c["pass"])
    score = round(passed / total * 100)

    return {"score": score, "issues": issues, "checks": checks}


# ============ NODE ENTRYPOINT ============

def builder_node(state: FactoryState) -> FactoryState:
    log = state.get("log", [])
    job_id = state.get("job_id", "unknown")

    # D2.4: bump iteration counter on retry
    iteration = state.get("iteration", 0)
    is_retry = bool(state.get("test_results", {}).get("failed", 0))
    if is_retry:
        iteration = iteration + 1
        log.append(f"⚙️  Builder: 看到 error · 進入 retry iteration {iteration}")
    else:
        log.append("⚙️  Builder: 開始 agent loop...")

    if is_mock():
        files = _builder_mock(state, job_id, iteration, log)
    else:
        files = _builder_real(state, job_id, iteration, log)

    return {
        **state,
        "files": files,
        "iteration": iteration,
        "current_stage": "tester",
        "log": log,
    }
